#!/bin/bash
# Auto-generated wrapper for Akto guardrails hook
# Generated by MCP Endpoint Shield installer

export MODE="atlas"
export AKTO_DATA_INGESTION_URL="http://localhost:9091"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export CONTEXT_SOURCE="ENDPOINT"
# Execute Python hook script
exec python3 "./.github/hooks/akto-validate-post-tool.py" "$@"
