
const STEPS_PER_AGENT_ID = {
    "FIND_VULNERABILITIES_FROM_SOURCE_CODE": 5,
    "FIND_APIS_FROM_SOURCE_CODE": 2,
    "FIND_SENSITIVE_DATA_TYPES": 1,
    "CREATE_TEST_TEMPLATES": 1,
    "GROUP_APIS": 1,
    "FIND_FALSE_POSITIVE": 1,
}

export default STEPS_PER_AGENT_ID