version: '2.1'

services:
  kafka1:
    image: public.ecr.aws/aktosecurity/confluentinc-cp-kafka:8.2.0-1-ubi9
    restart: always
    hostname: kafka1
    user: "0"
    ports:
      - "9092:9092"
      - "19092:19092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9094"
      KAFKA_CLUSTER_ID: "c6a1b8e2-4f2a-4b2a-9c3f-1a2b3c4d5e6f"
      KAFKA_LISTENERS: "CONTROLLER://0.0.0.0:9094,LISTENER_DOCKER_EXTERNAL_DIFFHOST://0.0.0.0:9092,LISTENER_DOCKER_INTERNAL://0.0.0.0:19092,LISTENER_DOCKER_EXTERNAL_LOCALHOST://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_EXTERNAL_DIFFHOST://${AKTO_KAFKA_IP}:9092, LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL_LOCALHOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_DOCKER_EXTERNAL_DIFFHOST:PLAINTEXT,LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL_LOCALHOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_BROKER_ID: "1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CREATE_TOPICS: "akto.api.logs:3:3"
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 60000
      KAFKA_LOG_RETENTION_HOURS: 5
      KAFKA_LOG_SEGMENT_BYTES: 104857600
      KAFKA_LOG_CLEANER_ENABLE: "true"
      KAFKA_CLEANUP_POLICY: "delete"
      KAFKA_LOG_RETENTION_BYTES: 10737418240
    volumes:
      - ./data-kafka-data:/var/lib/kafka/data
      - ./data-kafka-secrets:/etc/kafka/secrets
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "2"
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  akto-api-security-runtime:
    image: public.ecr.aws/aktosecurity/akto-api-security-mini-runtime:testruntime
    env_file: ./.env/docker-mini-runtime.env
    mem_limit: 8g
    restart: always
    depends_on:
      - kafka1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  data-ingestion-service:
    build:
      context: ../../data-ingestion-service
      dockerfile: Dockerfile
    env_file: ./.env/data-ingestion-docker.env
    mem_limit: 8g
    environment:
      GUARDRAILS_CLIENT_TIMEOUT_MS: "2000"
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - kafka1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  guardrails-service-http:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardrails-service-http
    env_file: ./.env/docker-guardrails-service.env
    restart: always
    ports:
      - "127.0.0.1:9091:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    labels:
      com.centurylinklabs.watchtower.enable: "false"
