version: '2.1'

services:
  akto-api-security-runtime:
    image: public.ecr.aws/aktosecurity/akto-api-security-mini-runtime:testruntime
    env_file: ./.env/docker-mini-runtime.env
    mem_limit: 8g
    restart: always
    depends_on:
      - kafka1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  data-ingestion-service:
    build:
      context: ../../data-ingestion-service
      dockerfile: Dockerfile
    env_file: ./.env/data-ingestion-docker.env
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - kafka1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  guardrails-service-http:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardrails-service-http
    env_file: ./.env/docker-guardrails-service.env
    restart: always
    ports:
      - "127.0.0.1:9091:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    labels:
      com.centurylinklabs.watchtower.enable: "false"
