// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/consumer_service/v1/consumer_service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.consumer_service.v1;

public interface SaveMaliciousEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threat_protection.consumer_service.v1.SaveMaliciousEventResponse)
    com.google.protobuf.MessageOrBuilder {
}
