import { Button, HorizontalStack, Text, Box, Icon, TextField, Checkbox, Tabs } from "@shopify/polaris"
import { EditMinor,SearchMinor } from '@shopify/polaris-icons';
import { useEffect, useMemo, useState } from "react";
import TestSuiteRow from "./TestSuiteRow";
import FlyLayout from "../../../components/layouts/FlyLayout";
import api from "../api";
import func from "../../../../../util/func";
import { debounce } from "lodash";
import LocalStore from "../../../../main/LocalStorageStore";
import transform from "./transform";

function FlyLayoutSuite(props) {
    const { show, setShow, selectedTestSuite, fetchTableData, createNewMode, setCreateNewMode } = props;
    const [testSuiteName, setTestSuiteName] = useState("");
    const [testSearchValue, setTestSearchValue] = useState("");
    const [categories, setCategories] = useState([]);
    const [filteredCategories, setFilteredCategories] = useState([]);
    const [inactiveCategories, setInactiveCategories] = useState([]);
    const [filteredInactiveCategories, setFilteredInactiveCategories] = useState([]);
    const [isEditMode, setIsEditMode] = useState(false);
    const [activeViewTab, setActiveViewTab] = useState(0);

    const handleExit = () => {
        setShow(false);
        setTestSearchValue("");
        setIsEditMode(false);
        setActiveViewTab(0);
        if(createNewMode===true) setCreateNewMode(false);
    }

    const buildCategoryList = (subCategoryMap) =>
        Object.values(subCategoryMap).map(tests => ({
            tests,
            displayName: tests[0]?.categoryName || "",
            selected: false,
        }));

    const getFlyLayoutListRows = async () => {
        const { activeSubCategoryMap } = await transform.getSubCategoryMap(LocalStore);
        return buildCategoryList(activeSubCategoryMap);
    }


    const handleTestSuiteSave = async () => {
        if (!testSuiteName || testSuiteName.trim().length === 0) {
            func.setToast(true, true, "Test Suite Name cannot be empty");
            return;
        }
        let selectedTestSuiteTests = [];
        categories.forEach(element => {
            element.tests.forEach(test => {
                if (test.selected === true) {
                    selectedTestSuiteTests.push(test.value);
                }
            });

        });

        // check if the test suite has changed
        let hasChanged = false;
        if (testSuiteName !== selectedTestSuite?.testSuiteName) hasChanged = true;
        if (selectedTestSuite?.tests && !func.deepArrayComparison(selectedTestSuiteTests, selectedTestSuite?.tests)) {
            hasChanged = true;
        }

        try {
            if (selectedTestSuite && hasChanged && !selectedTestSuite.isAutoGenerated) {
                await api.modifyTestSuite(selectedTestSuite.id, testSuiteName, selectedTestSuiteTests);
                func.setToast(true, false, "Test suite has been updated successfully.");
            } else if(createNewMode === true || selectedTestSuite?.isAutoGenerated){ 
                // (1) is appended to avoid duplicate names for autogenerated test suites
                let name = (selectedTestSuite?.isAutoGenerated && testSuiteName === selectedTestSuite?.testSuiteName) ? testSuiteName + ' (1)'  : testSuiteName;
                await api.createNewTestSuite(name, selectedTestSuiteTests);
                func.setToast(true, false, "Test suite has been created successfully.");
            }
        } catch (error) {
            func.setToast(true, true, "An error occurred while saving the test suite.");
        }

        fetchTableData();
        handleExit();
    }


    const filterToTestSuite = (categoryList, selectedTestSuiteTestsSet) =>
        categoryList.map(subCat => {
            const filteredTests = subCat.tests.filter(test => selectedTestSuiteTestsSet.has(test.value));
            if (filteredTests.length === 0) return null;
            return { ...subCat, tests: filteredTests };
        }).filter(Boolean);

    const updateTestSuite = async () => {
        const { activeSubCategoryMap, inactiveSubCategoryMap } = await transform.getSubCategoryMap(LocalStore);

        if (!selectedTestSuite?.tests) {
            setCategories([]);
            setInactiveCategories(buildCategoryList(inactiveSubCategoryMap));
            setTestSuiteName("");
            return;
        }

        const selectedTestSuiteTestsSet = new Set(selectedTestSuite.tests);
        setCategories(filterToTestSuite(buildCategoryList(activeSubCategoryMap), selectedTestSuiteTestsSet));
        setInactiveCategories(buildCategoryList(inactiveSubCategoryMap));
        setTestSuiteName(selectedTestSuite.testSuiteName || "");
    };

    
    useEffect(() => {
        updateTestSuite();
    }, [selectedTestSuite]);

    useEffect(() => {
        if(createNewMode === true) {
            setIsEditMode(true);
        }
        else setIsEditMode(false);
    }, [createNewMode]);


    const expandMatchingCategories = (setter, value) => {
        setter(prev => {
            const updated = [...prev];
            updated.forEach(category => {
                if (value.length > 0) {
                    if (category.tests.some(test => test.label.toLowerCase().includes(value.toLowerCase()))) {
                        category.selected = true;
                    }
                } else {
                    category.selected = false;
                }
            });
            return updated;
        });
    };

    const filteredList = (value) => {
        expandMatchingCategories(setCategories, value);
        expandMatchingCategories(setInactiveCategories, value);
    }

    const applySearchFilter = (source, searchValue) => {
        const deepCopy = source && Array.isArray(source) ? JSON.parse(JSON.stringify(source)) : [];
        return deepCopy.filter(category => {
            const tests = category.tests.filter(test =>
                test.label.toLowerCase().includes(searchValue.toLowerCase())
            );
            if (tests.length > 0) {
                category.tests = tests;
                return true;
            }
            return false;
        });
    };

    // filter the categories based on the search value
    useEffect(() => {
        setFilteredCategories(applySearchFilter(categories, testSearchValue));
    }, [categories]);

    useEffect(() => {
        setFilteredInactiveCategories(applySearchFilter(inactiveCategories, testSearchValue));
    }, [inactiveCategories]);


    async function handleSwitchMode() {
        if (!isEditMode) {
            updateTestSuite();
            return;
        }

        setInactiveCategories([]);

        const testSuiteSubCategoryMap = await getFlyLayoutListRows();

        const selectedTestSet = new Set(selectedTestSuite?.tests);
        testSuiteSubCategoryMap.forEach(category => {
            category.tests.forEach(test => {
                test.selected = createNewMode ? true : selectedTestSet.has(test.value);
            });
        });

        setCategories(testSuiteSubCategoryMap);
    }

    useEffect(() => {
        handleSwitchMode();
    }, [isEditMode]);


    const countSearchResults = () => {
        let count = 0;
        filteredCategories.forEach(category => { count += category.tests.length });
        filteredInactiveCategories.forEach(category => { count += category.tests.length });
        return count;
    }

    const isInactiveTab = !isEditMode && activeViewTab === 1;

    function checkExpand() {
        const list = isInactiveTab ? filteredInactiveCategories : filteredCategories;
        return list.some(category => !category.selected);
    }

    const debouncedSearch = useMemo(() => debounce(filteredList, 500), []);

    useEffect(() => {
        return () => debouncedSearch.cancel();
    }, []);
    

    const handleSearchChange = (val) => {
        setTestSearchValue(val); 
        debouncedSearch(val); 
    };

    const headingComponents = (
        <Box borderColor="border-subdued" borderBlockStartWidth="1" borderBlockEndWidth="1" background="bg-subdued" padding={4}>
            <HorizontalStack blockAlign="end" align="space-between" wrap={false}>
                <Box width="40%" >
                    <TextField maxLength={64} showCharacterCount disabled={!isEditMode} value={testSuiteName} onChange={(val) => setTestSuiteName(val)} label="Test Suite Name" placeholder="Test Suite Name" />
                </Box>
                <Box width="58%" paddingBlockStart={6}>
                    <TextField value={testSearchValue} onChange={(val) => { handleSearchChange(val)}} prefix={<Icon source={SearchMinor} />} placeholder="Search" />
                </Box>
            </HorizontalStack>
        </Box>
    )

    function extendAllHandler() {
        const setter = isInactiveTab ? setInactiveCategories : setCategories;
        setter(prev => prev.map(category => ({ ...category, selected: true })));
    }

    function collapseAllHandler() {
        const setter = isInactiveTab ? setInactiveCategories : setCategories;
        setter(prev => prev.map(category => ({ ...category, selected: false })));
    }

    function switchMode() {
        setIsEditMode(!isEditMode);
    }

    function countSelectedTest(){
        let count = 0;
        categories.forEach(category => {
            category?.tests?.forEach(test => {
                if(test.selected){
                    count++;
                }
            });
        });
        return count>1 ? `${count} tests` : `${count} test`;
    }

    function countSelectedCategories(){
        let count = 0;
        categories.forEach(category => {
            if(category?.tests?.some(test => test.selected)) count++;
        });
        return count>1 ? `${count} categories` : `${count} category`;
    }

    function checkAllCategoriesSelected() {
        let atleastOne = false;
        let allSelected = true;
        const updatedCategories = [...filteredCategories];
        updatedCategories.forEach(element => {
            element.tests.forEach(test => {
                if (!test.selected) {
                    allSelected = false;
                }
                if (test.selected) {
                    atleastOne = true;
                }
            });
        });
        if (atleastOne && allSelected) return true;
        else if (atleastOne) return "indeterminate";
        else return false;
    }

    function selectAllCategories() {
        setCategories(prev => {
            const updatedCategories = [...prev];

            let someSelected = false;
            updatedCategories.forEach(element => {
                element.tests.some(test => {
                    if (test.selected) {
                        someSelected = true;
                    }
                });

            });

            const selectedFromFilterCategories = new Set();
            filteredCategories.forEach(element => {
                element.tests.forEach(test => {
                    selectedFromFilterCategories.add(test.value);
                });
            });

            updatedCategories.forEach(element => {
                element.tests.forEach(test => {
                    if (selectedFromFilterCategories.has(test.value))
                        test.selected = someSelected ? false : true;
                });

            });
            return updatedCategories;
        }
        );

    }

    const activeTestsCount = filteredCategories.reduce((sum, cat) => sum + cat.tests.length, 0);
    const inactiveTestsCount = filteredInactiveCategories.reduce((sum, cat) => sum + cat.tests.length, 0);

    const viewTabs = [
        { id: "active", content: `Active (${activeTestsCount})` },
        { id: "inactive", content: `Inactive (${inactiveTestsCount})` },
    ];

    const listComponents = (
        <Box borderRadius="2" borderColor="border-subdued" style={{ margin: "20px", boxShadow: "0px 0px 5px 0px #0000000D, 0px 1px 2px 0px #00000026" }}>
                {!isEditMode && (
                    <Tabs tabs={viewTabs} selected={activeViewTab} onSelect={setActiveViewTab} />
                )}
                <Box borderColor="border-subdued" paddingBlockEnd={3} paddingBlockStart={3} paddingInlineStart={5} paddingInlineEnd={5}>
                    <HorizontalStack align="space-between">
                        <HorizontalStack align="start">
                            {isEditMode && <Checkbox checked={checkAllCategoriesSelected()} onChange={() => { selectAllCategories()}} />}
                            <Text color="subdued" fontWeight="semibold" as="h3">
                                {testSearchValue.length > 0
                                    ? `Showing ${countSearchResults()} result`
                                    : isEditMode
                                        ? `${countSelectedTest()} from ${countSelectedCategories()} selected`
                                        : activeViewTab === 0
                                            ? `${filteredCategories.length} ${filteredCategories.length > 1 ? 'categories' : 'category'} & ${activeTestsCount} tests`
                                            : `${filteredInactiveCategories.length} ${filteredInactiveCategories.length > 1 ? 'categories' : 'category'} & ${inactiveTestsCount} tests`}
                            </Text>
                        </HorizontalStack>
                        {testSearchValue.trim().length === 0 && <Button onClick={() => { checkExpand() ? extendAllHandler() : collapseAllHandler() }} plain><Text>{checkExpand() ? "Expand all" : "Collapse all"}</Text></Button>}
                    </HorizontalStack>
                </Box>
                {(isEditMode || activeViewTab === 0) && filteredCategories.map((category, index) => (
                    <TestSuiteRow
                        filteredCategories={filteredCategories}
                        categories={categories}
                        isEditMode={isEditMode}
                        isLast={index === filteredCategories.length - 1}
                        key={index}
                        category={category}
                        setCategories={setCategories}
                        setFilteredCategories={setFilteredCategories}
                    />
                ))}
                {!isEditMode && activeViewTab === 1 && filteredInactiveCategories.map((category, index) => (
                    <TestSuiteRow
                        filteredCategories={filteredInactiveCategories}
                        categories={inactiveCategories}
                        isEditMode={false}
                        isLast={index === filteredInactiveCategories.length - 1}
                        key={`inactive-${index}`}
                        category={category}
                        setCategories={setInactiveCategories}
                        setFilteredCategories={setFilteredInactiveCategories}
                    />
                ))}
        </Box>
    );

    const footer = isEditMode ? (
        <Box background="bg" borderColor="border-subdued" borderBlockStartWidth="1" padding="4" style={{ position: "fixed", bottom: "0", zIndex: 10, width: "50vw" }}>
            <HorizontalStack align="end" gap="3">
                <Button onClick={switchMode}>Cancel</Button>
                <Button primary onClick={() => handleTestSuiteSave()}>Save</Button>
            </HorizontalStack>
        </Box>
    ) : null;


    const components = [headingComponents, listComponents,footer].filter(Boolean);

    const titleComp = (
        <Box width="96%">
            <HorizontalStack align="space-between">

                <Text variant="headingMd">
                    Test Suite
                </Text>
                {selectedTestSuite && (
                    <Button icon={EditMinor} onClick={switchMode} plain></Button>
                )}
            </HorizontalStack>
        </Box>
    )



    return (
        <FlyLayout
            titleComp={titleComp}
            show={show}
            setShow={setShow}
            components={components}
            handleClose={handleExit}
            loading={false}
            showDivider={false}
            newComp={true}
            isHandleClose={true}
            switchMode={switchMode}
            variant={"testSuiteFlyout"}>
        </FlyLayout>
    )
}


export default FlyLayoutSuite;