// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/consumer_service/v1/consumer_service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.consumer_service.v1;

/**
 * Protobuf type {@code threat_protection.service.consumer_service.v1.RecordAlertRequest}
 */
public final class RecordAlertRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threat_protection.service.consumer_service.v1.RecordAlertRequest)
    RecordAlertRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      RecordAlertRequest.class.getName());
  }
  // Use RecordAlertRequest.newBuilder() to construct.
  private RecordAlertRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RecordAlertRequest() {
    actor_ = "";
    filterId_ = "";
    sampleData_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.akto.proto.threat_protection.service.consumer_service.v1.ConsumerServiceProto.internal_static_threat_protection_service_consumer_service_v1_RecordAlertRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.akto.proto.threat_protection.service.consumer_service.v1.ConsumerServiceProto.internal_static_threat_protection_service_consumer_service_v1_RecordAlertRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest.class, com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest.Builder.class);
  }

  public static final int ACTOR_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actor_ = "";
  /**
   * <code>string actor = 1 [json_name = "actor"];</code>
   * @return The actor.
   */
  @java.lang.Override
  public java.lang.String getActor() {
    java.lang.Object ref = actor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actor_ = s;
      return s;
    }
  }
  /**
   * <code>string actor = 1 [json_name = "actor"];</code>
   * @return The bytes for actor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorBytes() {
    java.lang.Object ref = actor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILTER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object filterId_ = "";
  /**
   * <code>string filter_id = 2 [json_name = "filterId"];</code>
   * @return The filterId.
   */
  @java.lang.Override
  public java.lang.String getFilterId() {
    java.lang.Object ref = filterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filterId_ = s;
      return s;
    }
  }
  /**
   * <code>string filter_id = 2 [json_name = "filterId"];</code>
   * @return The bytes for filterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilterIdBytes() {
    java.lang.Object ref = filterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_EVENTS_FIELD_NUMBER = 3;
  private int totalEvents_ = 0;
  /**
   * <code>int32 total_events = 3 [json_name = "totalEvents"];</code>
   * @return The totalEvents.
   */
  @java.lang.Override
  public int getTotalEvents() {
    return totalEvents_;
  }

  public static final int DETECTED_AT_FIELD_NUMBER = 4;
  private long detectedAt_ = 0L;
  /**
   * <code>int64 detected_at = 4 [json_name = "detectedAt"];</code>
   * @return The detectedAt.
   */
  @java.lang.Override
  public long getDetectedAt() {
    return detectedAt_;
  }

  public static final int SAMPLE_DATA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent> sampleData_;
  /**
   * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  @java.lang.Override
  public java.util.List<com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent> getSampleDataList() {
    return sampleData_;
  }
  /**
   * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEventOrBuilder> 
      getSampleDataOrBuilderList() {
    return sampleData_;
  }
  /**
   * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  @java.lang.Override
  public int getSampleDataCount() {
    return sampleData_.size();
  }
  /**
   * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  @java.lang.Override
  public com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent getSampleData(int index) {
    return sampleData_.get(index);
  }
  /**
   * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  @java.lang.Override
  public com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEventOrBuilder getSampleDataOrBuilder(
      int index) {
    return sampleData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actor_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, actor_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filterId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, filterId_);
    }
    if (totalEvents_ != 0) {
      output.writeInt32(3, totalEvents_);
    }
    if (detectedAt_ != 0L) {
      output.writeInt64(4, detectedAt_);
    }
    for (int i = 0; i < sampleData_.size(); i++) {
      output.writeMessage(5, sampleData_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actor_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, actor_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filterId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, filterId_);
    }
    if (totalEvents_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalEvents_);
    }
    if (detectedAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, detectedAt_);
    }
    for (int i = 0; i < sampleData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, sampleData_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest)) {
      return super.equals(obj);
    }
    com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest other = (com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest) obj;

    if (!getActor()
        .equals(other.getActor())) return false;
    if (!getFilterId()
        .equals(other.getFilterId())) return false;
    if (getTotalEvents()
        != other.getTotalEvents()) return false;
    if (getDetectedAt()
        != other.getDetectedAt()) return false;
    if (!getSampleDataList()
        .equals(other.getSampleDataList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTOR_FIELD_NUMBER;
    hash = (53 * hash) + getActor().hashCode();
    hash = (37 * hash) + FILTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFilterId().hashCode();
    hash = (37 * hash) + TOTAL_EVENTS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalEvents();
    hash = (37 * hash) + DETECTED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDetectedAt());
    if (getSampleDataCount() > 0) {
      hash = (37 * hash) + SAMPLE_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getSampleDataList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code threat_protection.service.consumer_service.v1.RecordAlertRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threat_protection.service.consumer_service.v1.RecordAlertRequest)
      com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akto.proto.threat_protection.service.consumer_service.v1.ConsumerServiceProto.internal_static_threat_protection_service_consumer_service_v1_RecordAlertRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akto.proto.threat_protection.service.consumer_service.v1.ConsumerServiceProto.internal_static_threat_protection_service_consumer_service_v1_RecordAlertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest.class, com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest.Builder.class);
    }

    // Construct using com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      actor_ = "";
      filterId_ = "";
      totalEvents_ = 0;
      detectedAt_ = 0L;
      if (sampleDataBuilder_ == null) {
        sampleData_ = java.util.Collections.emptyList();
      } else {
        sampleData_ = null;
        sampleDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.akto.proto.threat_protection.service.consumer_service.v1.ConsumerServiceProto.internal_static_threat_protection_service_consumer_service_v1_RecordAlertRequest_descriptor;
    }

    @java.lang.Override
    public com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest getDefaultInstanceForType() {
      return com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest build() {
      com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest buildPartial() {
      com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest result = new com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest result) {
      if (sampleDataBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          sampleData_ = java.util.Collections.unmodifiableList(sampleData_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.sampleData_ = sampleData_;
      } else {
        result.sampleData_ = sampleDataBuilder_.build();
      }
    }

    private void buildPartial0(com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.actor_ = actor_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.filterId_ = filterId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalEvents_ = totalEvents_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.detectedAt_ = detectedAt_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest) {
        return mergeFrom((com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest other) {
      if (other == com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest.getDefaultInstance()) return this;
      if (!other.getActor().isEmpty()) {
        actor_ = other.actor_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFilterId().isEmpty()) {
        filterId_ = other.filterId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTotalEvents() != 0) {
        setTotalEvents(other.getTotalEvents());
      }
      if (other.getDetectedAt() != 0L) {
        setDetectedAt(other.getDetectedAt());
      }
      if (sampleDataBuilder_ == null) {
        if (!other.sampleData_.isEmpty()) {
          if (sampleData_.isEmpty()) {
            sampleData_ = other.sampleData_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSampleDataIsMutable();
            sampleData_.addAll(other.sampleData_);
          }
          onChanged();
        }
      } else {
        if (!other.sampleData_.isEmpty()) {
          if (sampleDataBuilder_.isEmpty()) {
            sampleDataBuilder_.dispose();
            sampleDataBuilder_ = null;
            sampleData_ = other.sampleData_;
            bitField0_ = (bitField0_ & ~0x00000010);
            sampleDataBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSampleDataFieldBuilder() : null;
          } else {
            sampleDataBuilder_.addAllMessages(other.sampleData_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              actor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              filterId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              totalEvents_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              detectedAt_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent m =
                  input.readMessage(
                      com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.parser(),
                      extensionRegistry);
              if (sampleDataBuilder_ == null) {
                ensureSampleDataIsMutable();
                sampleData_.add(m);
              } else {
                sampleDataBuilder_.addMessage(m);
              }
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object actor_ = "";
    /**
     * <code>string actor = 1 [json_name = "actor"];</code>
     * @return The actor.
     */
    public java.lang.String getActor() {
      java.lang.Object ref = actor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string actor = 1 [json_name = "actor"];</code>
     * @return The bytes for actor.
     */
    public com.google.protobuf.ByteString
        getActorBytes() {
      java.lang.Object ref = actor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string actor = 1 [json_name = "actor"];</code>
     * @param value The actor to set.
     * @return This builder for chaining.
     */
    public Builder setActor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actor_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string actor = 1 [json_name = "actor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActor() {
      actor_ = getDefaultInstance().getActor();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string actor = 1 [json_name = "actor"];</code>
     * @param value The bytes for actor to set.
     * @return This builder for chaining.
     */
    public Builder setActorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actor_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object filterId_ = "";
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @return The filterId.
     */
    public java.lang.String getFilterId() {
      java.lang.Object ref = filterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @return The bytes for filterId.
     */
    public com.google.protobuf.ByteString
        getFilterIdBytes() {
      java.lang.Object ref = filterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @param value The filterId to set.
     * @return This builder for chaining.
     */
    public Builder setFilterId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      filterId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFilterId() {
      filterId_ = getDefaultInstance().getFilterId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @param value The bytes for filterId to set.
     * @return This builder for chaining.
     */
    public Builder setFilterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      filterId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int totalEvents_ ;
    /**
     * <code>int32 total_events = 3 [json_name = "totalEvents"];</code>
     * @return The totalEvents.
     */
    @java.lang.Override
    public int getTotalEvents() {
      return totalEvents_;
    }
    /**
     * <code>int32 total_events = 3 [json_name = "totalEvents"];</code>
     * @param value The totalEvents to set.
     * @return This builder for chaining.
     */
    public Builder setTotalEvents(int value) {

      totalEvents_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_events = 3 [json_name = "totalEvents"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalEvents() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalEvents_ = 0;
      onChanged();
      return this;
    }

    private long detectedAt_ ;
    /**
     * <code>int64 detected_at = 4 [json_name = "detectedAt"];</code>
     * @return The detectedAt.
     */
    @java.lang.Override
    public long getDetectedAt() {
      return detectedAt_;
    }
    /**
     * <code>int64 detected_at = 4 [json_name = "detectedAt"];</code>
     * @param value The detectedAt to set.
     * @return This builder for chaining.
     */
    public Builder setDetectedAt(long value) {

      detectedAt_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 detected_at = 4 [json_name = "detectedAt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDetectedAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      detectedAt_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent> sampleData_ =
      java.util.Collections.emptyList();
    private void ensureSampleDataIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        sampleData_ = new java.util.ArrayList<com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent>(sampleData_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEventOrBuilder> sampleDataBuilder_;

    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public java.util.List<com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent> getSampleDataList() {
      if (sampleDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sampleData_);
      } else {
        return sampleDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public int getSampleDataCount() {
      if (sampleDataBuilder_ == null) {
        return sampleData_.size();
      } else {
        return sampleDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent getSampleData(int index) {
      if (sampleDataBuilder_ == null) {
        return sampleData_.get(index);
      } else {
        return sampleDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public Builder setSampleData(
        int index, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent value) {
      if (sampleDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSampleDataIsMutable();
        sampleData_.set(index, value);
        onChanged();
      } else {
        sampleDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public Builder setSampleData(
        int index, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder builderForValue) {
      if (sampleDataBuilder_ == null) {
        ensureSampleDataIsMutable();
        sampleData_.set(index, builderForValue.build());
        onChanged();
      } else {
        sampleDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public Builder addSampleData(com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent value) {
      if (sampleDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSampleDataIsMutable();
        sampleData_.add(value);
        onChanged();
      } else {
        sampleDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public Builder addSampleData(
        int index, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent value) {
      if (sampleDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSampleDataIsMutable();
        sampleData_.add(index, value);
        onChanged();
      } else {
        sampleDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public Builder addSampleData(
        com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder builderForValue) {
      if (sampleDataBuilder_ == null) {
        ensureSampleDataIsMutable();
        sampleData_.add(builderForValue.build());
        onChanged();
      } else {
        sampleDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public Builder addSampleData(
        int index, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder builderForValue) {
      if (sampleDataBuilder_ == null) {
        ensureSampleDataIsMutable();
        sampleData_.add(index, builderForValue.build());
        onChanged();
      } else {
        sampleDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public Builder addAllSampleData(
        java.lang.Iterable<? extends com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent> values) {
      if (sampleDataBuilder_ == null) {
        ensureSampleDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sampleData_);
        onChanged();
      } else {
        sampleDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public Builder clearSampleData() {
      if (sampleDataBuilder_ == null) {
        sampleData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        sampleDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public Builder removeSampleData(int index) {
      if (sampleDataBuilder_ == null) {
        ensureSampleDataIsMutable();
        sampleData_.remove(index);
        onChanged();
      } else {
        sampleDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder getSampleDataBuilder(
        int index) {
      return getSampleDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEventOrBuilder getSampleDataOrBuilder(
        int index) {
      if (sampleDataBuilder_ == null) {
        return sampleData_.get(index);  } else {
        return sampleDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public java.util.List<? extends com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEventOrBuilder> 
         getSampleDataOrBuilderList() {
      if (sampleDataBuilder_ != null) {
        return sampleDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sampleData_);
      }
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder addSampleDataBuilder() {
      return getSampleDataFieldBuilder().addBuilder(
          com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder addSampleDataBuilder(
        int index) {
      return getSampleDataFieldBuilder().addBuilder(
          index, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .threat_protection.service.consumer_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
     */
    public java.util.List<com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder> 
         getSampleDataBuilderList() {
      return getSampleDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEventOrBuilder> 
        getSampleDataFieldBuilder() {
      if (sampleDataBuilder_ == null) {
        sampleDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEvent.Builder, com.akto.proto.threat_protection.service.consumer_service.v1.SampleMaliciousEventOrBuilder>(
                sampleData_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        sampleData_ = null;
      }
      return sampleDataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:threat_protection.service.consumer_service.v1.RecordAlertRequest)
  }

  // @@protoc_insertion_point(class_scope:threat_protection.service.consumer_service.v1.RecordAlertRequest)
  private static final com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest();
  }

  public static com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecordAlertRequest>
      PARSER = new com.google.protobuf.AbstractParser<RecordAlertRequest>() {
    @java.lang.Override
    public RecordAlertRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecordAlertRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecordAlertRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.akto.proto.threat_protection.service.consumer_service.v1.RecordAlertRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

