#!/usr/bin/env bash
# install-shell-hooks.sh - install the Akto cursor SHELL hooks (no python, no jq).
#
# Deploys the bash hooks + shared lib into ~/.cursor/hooks/akto, generates
# runtime-detecting wrapper scripts, and writes ~/.cursor/hooks.json wiring the
# cursor hook events to the wrappers.
#
# Works fully offline from a local checkout. Designed to coexist with the
# existing Python installer: wrappers prefer python3 when present, else run the
# shell hook. Force shell with AKTO_HOOK_RUNTIME=shell.
#
# Usage:
#   install-shell-hooks.sh [--ingestion-url URL] [--device-id ID] [--home DIR] [--src DIR] [--api-token TOKEN]
set -eu

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INGESTION_URL="${AKTO_DATA_INGESTION_URL:-}"
DEVICE_ID="${DEVICE_ID:-}"
API_TOKEN="${AKTO_API_TOKEN:-}"
TARGET_HOME="$HOME"
SRC_BASH="$SRC_DIR/bash"

while [ $# -gt 0 ]; do
  case "$1" in
    --ingestion-url) INGESTION_URL="$2"; shift 2;;
    --device-id) DEVICE_ID="$2"; shift 2;;
    --home) TARGET_HOME="$2"; shift 2;;
    --src) SRC_BASH="$2"; shift 2;;
    --api-token) API_TOKEN="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

HOOKS_DIR="$TARGET_HOME/.cursor/hooks/akto"
HOOKS_JSON="$TARGET_HOME/.cursor/hooks.json"
log() { echo "[Akto cursor shell-hooks] $1"; }

# device label (hostname-first8 of machine id), mirrors generate_device_label()
if [ -z "$DEVICE_ID" ]; then
  _name="$(scutil --get ComputerName 2>/dev/null | tr ' ' '-')"
  [ -z "$_name" ] && _name="$(hostname 2>/dev/null | sed 's/\.local$//' | tr ' ' '-')"
  _mid=""
  if command -v ioreg >/dev/null 2>&1; then
    _mid="$(ioreg -rd1 -c IOPlatformExpertDevice 2>/dev/null | grep IOPlatformUUID | awk -F'"' '{print $4}' | tr -d '-' | tr '[:upper:]' '[:lower:]')"
  fi
  [ -z "$_mid" ] && [ -r /etc/machine-id ] && _mid="$(tr -d '-' < /etc/machine-id)"
  DEVICE_ID="${_name}-${_mid:0:8}"
fi

mkdir -p "$HOOKS_DIR"
log "Hooks dir: $HOOKS_DIR"

# 1) copy shell hooks + shared lib
for f in akto_common.sh akto-validate-chat-prompt.sh akto-validate-chat-response.sh \
         akto-validate-mcp-request.sh akto-validate-mcp-response.sh akto-hooks.sh; do
  cp "$SRC_BASH/$f" "$HOOKS_DIR/$f"
  chmod +x "$HOOKS_DIR/$f"
done
log "Installed bash hooks + akto_common.sh"

# common env block emitted into each wrapper
emit_env() {
  cat <<EOF
export MODE="atlas"
export AKTO_DATA_INGESTION_URL="$INGESTION_URL"
export AKTO_API_TOKEN="$API_TOKEN"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="cursor"
export AKTO_CONNECTOR_VALUE="cursor"
export CONTEXT_SOURCE="ENDPOINT"
export DEVICE_ID="$DEVICE_ID"
export LOG_LEVEL="INFO"
export LOG_PAYLOADS="false"
EOF
}

# 2) generate a runtime-detecting wrapper for a validate hook
#    $1=wrapper basename (chat-prompt|chat-response|mcp-request|mcp-response)
#    $2=python script basename   $3=shell script basename
make_wrapper() {
  local name="$1" pyfile="$2" shfile="$3"
  local wf="$HOOKS_DIR/akto-validate-${name}-wrapper.sh"
  {
    echo "#!/bin/bash"
    echo "# Auto-generated by Akto cursor shell-hooks installer (runtime-detecting)"
    emit_env
    cat <<EOF

HOOKS_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
if command -v python3 >/dev/null 2>&1 && [ "\${AKTO_HOOK_RUNTIME:-}" != "shell" ] && [ -f "\$HOOKS_DIR/$pyfile" ]; then
  exec python3 "\$HOOKS_DIR/$pyfile" "\$@"
else
  exec bash "\$HOOKS_DIR/$shfile" "\$@"
fi
EOF
  } > "$wf"
  chmod +x "$wf"
}

make_wrapper chat-prompt   akto-validate-chat-prompt.py   akto-validate-chat-prompt.sh
make_wrapper chat-response akto-validate-chat-response.py akto-validate-chat-response.sh
make_wrapper mcp-request   akto-validate-mcp-request.py   akto-validate-mcp-request.sh
make_wrapper mcp-response  akto-validate-mcp-response.py  akto-validate-mcp-response.sh
log "Generated runtime-detecting validate wrappers"

# observability wrapper: akto-hook-wrapper.sh <pyscript> <hookName>
{
  echo "#!/bin/bash"
  echo "# Auto-generated by Akto cursor shell-hooks installer (runtime-detecting)"
  emit_env
  cat <<EOF

HOOKS_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
HOOK_EVENT="\$2"; [ -z "\$HOOK_EVENT" ] && HOOK_EVENT="\$1"
if command -v python3 >/dev/null 2>&1 && [ "\${AKTO_HOOK_RUNTIME:-}" != "shell" ] && [ -f "\$HOOKS_DIR/akto-hooks.py" ]; then
  exec python3 "\$HOOKS_DIR/akto-hooks.py" "\$HOOK_EVENT"
else
  exec bash "\$HOOKS_DIR/akto-hooks.sh" "\$HOOK_EVENT"
fi
EOF
} > "$HOOKS_DIR/akto-hook-wrapper.sh"
chmod +x "$HOOKS_DIR/akto-hook-wrapper.sh"
log "Generated observability wrapper"

# 3) write cursor hooks.json. Cursor schema: { "version":1, "hooks": { <event>:[{command,type,timeout[,failClosed]}] } }
P="bash $HOOKS_DIR/akto-validate-chat-prompt-wrapper.sh"
R="bash $HOOKS_DIR/akto-validate-chat-response-wrapper.sh"
PRE="bash $HOOKS_DIR/akto-validate-mcp-request-wrapper.sh"
POST="bash $HOOKS_DIR/akto-validate-mcp-response-wrapper.sh"
OBS="bash $HOOKS_DIR/akto-hook-wrapper.sh akto-hooks.py"
[ -f "$HOOKS_JSON" ] && cp "$HOOKS_JSON" "$HOOKS_JSON.backup.$(date +%s)" && log "Backed up existing hooks.json"
mkdir -p "$(dirname "$HOOKS_JSON")"

# observability event helper
obs_event() { printf '    "%s": [ { "command": "%s %s", "type": "command", "timeout": 10 } ]' "$1" "$OBS" "$1"; }

{
  echo '{'
  echo '  "version": 1,'
  echo '  "hooks": {'
  echo "    \"beforeSubmitPrompt\": [ { \"command\": \"$P\", \"type\": \"command\", \"timeout\": 20 } ],"
  echo "    \"afterAgentResponse\": [ { \"command\": \"$R\", \"type\": \"command\", \"timeout\": 20 } ],"
  echo "    \"beforeMCPExecution\": [ { \"command\": \"$PRE\", \"type\": \"command\", \"timeout\": 20, \"failClosed\": true } ],"
  echo "    \"afterMCPExecution\": [ { \"command\": \"$POST\", \"type\": \"command\", \"timeout\": 20 } ],"
  for ev in sessionStart sessionEnd preToolUse postToolUse postToolUseFailure subagentStart subagentStop \
            beforeShellExecution afterShellExecution beforeReadFile afterFileEdit afterAgentThought \
            stop preCompact beforeTabFileRead; do
    obs_event "$ev"; echo ','
  done
  # last observability event without trailing comma
  obs_event "afterTabFileEdit"; echo ''
  echo '  }'
  echo '}'
} > "$HOOKS_JSON"
log "Wrote hooks.json"
log "Done. Runtime: shell when python3 absent (or AKTO_HOOK_RUNTIME=shell)."
