// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/message/malicious_event/event_type/v1/event_type.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.message.malicious_event.event_type.v1;

public final class EventTypeProto {
  private EventTypeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      EventTypeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nHthreat_protection/message/malicious_ev" +
      "ent/event_type/v1/event_type.proto\0227thre" +
      "at_protection.message.malicious_event.ev" +
      "ent_type.v1*Y\n\tEventType\022\032\n\026EVENT_TYPE_U" +
      "NSPECIFIED\020\000\022\025\n\021EVENT_TYPE_SINGLE\020\001\022\031\n\025E" +
      "VENT_TYPE_AGGREGATED\020\002B\315\002\nFcom.akto.prot" +
      "o.threat_protection.message.malicious_ev" +
      "ent.event_type.v1B\016EventTypeProtoP\001\242\002\004TM" +
      "ME\252\0024ThreatProtection.Message.MaliciousE" +
      "vent.EventType.V1\312\0024ThreatProtection\\Mes" +
      "sage\\MaliciousEvent\\EventType\\V1\342\002@Threa" +
      "tProtection\\Message\\MaliciousEvent\\Event" +
      "Type\\V1\\GPBMetadata\352\0028ThreatProtection::" +
      "Message::MaliciousEvent::EventType::V1b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
