# Auto-generated wrapper for Akto guardrails hook (global installation)
# Generated by MCP Endpoint Shield installer

$env:MODE = "atlas"
$env:AKTO_DATA_INGESTION_URL = "{{AKTO_DATA_INGESTION_URL}}"
$env:AKTO_SYNC_MODE = "true"
$env:AKTO_TIMEOUT = "5"
$env:CONTEXT_SOURCE = "ENDPOINT"
$env:AKTO_TOKEN = "{{AKTO_API_TOKEN}}"
$env:LOG_DIR = "$env:USERPROFILE\github\hooks\logs"

# Execute Python hook script
python "$env:USERPROFILE\github\hooks\akto-validate-pre-tool.py" @args
