// Trims fabricated endpoint-shield devices (and their regular-mongo footprint) DOWN to TARGET total.
// Source/template devices (those present in the SRC account) are never removed. NHI / traces / threat
// are regenerated by their own scalers (wipe+rebuild for the current roster) — so after trimming you
// MUST re-run: run.sh <N> nhi, traces.sh load, threat.sh scale (rescale.sh does this for you).
// Connected to NEW_ACCT db. Config injected: TARGET, SRC (source acct db name)
(function () {
  const src = db.getSiblingDB(String(SRC));
  function esc(x) { return String(x).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }

  const srcNames = new Set(src.module_info.find({ moduleType: "MCP_ENDPOINT_SHIELD" }, { name: 1 }).toArray().map(d => d.name));
  const devices = db.module_info.find({ moduleType: "MCP_ENDPOINT_SHIELD" }).toArray();
  const fabricated = devices.filter(d => !srcNames.has(d.name));
  const current = devices.length;
  const toRemove = current - TARGET;
  if (toRemove <= 0) { print("current=" + current + " target=" + TARGET + " -> nothing to trim (use `run.sh " + TARGET + " fabricate` to scale UP)"); return; }
  if (toRemove > fabricated.length) print("WARNING: target " + TARGET + " is below the source device count (" + srcNames.size + "); only fabricated devices can be trimmed. Removing all " + fabricated.length + ".");

  const remove = fabricated.slice(0, Math.min(toRemove, fabricated.length));
  print("current=" + current + " target=" + TARGET + " -> removing " + remove.length + " fabricated devices + their regular-mongo footprint");

  const stats = {};
  function bump(k, v) { stats[k] = (stats[k] || 0) + (v || 0); }

  remove.forEach(function (dev, i) {
    const host = dev.name;
    const hw = dev.additionalData && dev.additionalData.deviceId;
    const colls = db.api_collections.find({ hostName: new RegExp("^" + esc(host) + "\\.") }, { _id: 1 }).toArray().map(c => c._id);
    if (colls.length) {
      bump("single_type_info", db.single_type_info.deleteMany({ $or: [{ apiCollectionId: { $in: colls } }, { collectionIds: { $in: colls } }] }).deletedCount);
      bump("api_info", db.api_info.deleteMany({ $or: [{ "_id.apiCollectionId": { $in: colls } }, { collectionIds: { $in: colls } }] }).deletedCount);
      bump("sample_data", db.sample_data.deleteMany({ $or: [{ "_id.apiCollectionId": { $in: colls } }, { collectionIds: { $in: colls } }] }).deletedCount);
      bump("sensitive_sample_data", db.sensitive_sample_data.deleteMany({ "_id.apiCollectionId": { $in: colls } }).deletedCount);
      bump("traffic_info", db.traffic_info.deleteMany({ "_id.apiCollectionId": { $in: colls } }).deletedCount);
      bump("mcp_audit_info", db.mcp_audit_info.deleteMany({ hostCollectionId: { $in: colls } }).deletedCount);
      bump("api_collections", db.api_collections.deleteMany({ _id: { $in: colls } }).deletedCount);
    }
    bump("endpoint_mcp_config", db.endpoint_mcp_config.deleteMany({ collectionName: new RegExp("^" + esc(host) + "\\.") }).deletedCount);
    bump("agent_users", db.agent_users.deleteMany({ devices: host }).deletedCount);
    if (hw) bump("user_analysis_data", db.user_analysis_data.deleteMany({ "_id.deviceId": hw }).deletedCount);
    bump("module_info", db.module_info.deleteMany({ _id: dev._id }).deletedCount);
    if ((i + 1) % 50 === 0 || i + 1 === remove.length) print("  ... trimmed " + (i + 1) + "/" + remove.length);
  });

  print("\n==== trimmed doc counts ====");
  Object.keys(stats).sort().forEach(k => print("  " + k + ": " + stats[k]));
  print("Devices now: " + db.module_info.countDocuments({ moduleType: "MCP_ENDPOINT_SHIELD" }));
  print("NOTE: re-run NHI/traces/threat scalers to regenerate their data for the remaining devices.");
})();
