CREATE SCHEMA IF NOT EXISTS THREAT_DETECTION;
CREATE TABLE IF NOT EXISTS THREAT_DETECTION.MALICIOUS_EVENTS (
    ID VARCHAR(36) PRIMARY KEY,
    ACTOR VARCHAR(255),
    FILTER_ID VARCHAR(255),
    URL VARCHAR(1024),
    IP VARCHAR(255),
    METHOD VARCHAR(255),
    TIMESTAMP BIGINT,
    ORIG TEXT
);

-- add index on actor and filter_id and sort data by timestamp
CREATE INDEX MALICIOUS_EVENTS_ACTOR_FILTER_ID_TIMESTAMP_IDX ON THREAT_DETECTION.MALICIOUS_EVENTS(ACTOR, FILTER_ID, TIMESTAMP DESC);
