// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: smart_event/v1/smart_event.proto
// Protobuf Java Version: 4.28.3

package io.akto.proto.smart_event.v1;

/**
 * Protobuf type {@code smart_event.v1.SmartEvent}
 */
public final class SmartEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:smart_event.v1.SmartEvent)
    SmartEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      SmartEvent.class.getName());
  }
  // Use SmartEvent.newBuilder() to construct.
  private SmartEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SmartEvent() {
    actorId_ = "";
    filterId_ = "";
    reason_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.akto.proto.smart_event.v1.SmartEventProto.internal_static_smart_event_v1_SmartEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.akto.proto.smart_event.v1.SmartEventProto.internal_static_smart_event_v1_SmartEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.akto.proto.smart_event.v1.SmartEvent.class, io.akto.proto.smart_event.v1.SmartEvent.Builder.class);
  }

  public static final int ACTOR_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actorId_ = "";
  /**
   * <code>string actor_id = 1 [json_name = "actorId"];</code>
   * @return The actorId.
   */
  @java.lang.Override
  public java.lang.String getActorId() {
    java.lang.Object ref = actorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actorId_ = s;
      return s;
    }
  }
  /**
   * <code>string actor_id = 1 [json_name = "actorId"];</code>
   * @return The bytes for actorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorIdBytes() {
    java.lang.Object ref = actorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILTER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object filterId_ = "";
  /**
   * <code>string filter_id = 2 [json_name = "filterId"];</code>
   * @return The filterId.
   */
  @java.lang.Override
  public java.lang.String getFilterId() {
    java.lang.Object ref = filterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filterId_ = s;
      return s;
    }
  }
  /**
   * <code>string filter_id = 2 [json_name = "filterId"];</code>
   * @return The bytes for filterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilterIdBytes() {
    java.lang.Object ref = filterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETECTED_TIMESTAMP_FIELD_NUMBER = 3;
  private long detectedTimestamp_ = 0L;
  /**
   * <code>int64 detected_timestamp = 3 [json_name = "detectedTimestamp"];</code>
   * @return The detectedTimestamp.
   */
  @java.lang.Override
  public long getDetectedTimestamp() {
    return detectedTimestamp_;
  }

  public static final int REASON_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reason_ = "";
  /**
   * <code>string reason = 4 [json_name = "reason"];</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    java.lang.Object ref = reason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reason_ = s;
      return s;
    }
  }
  /**
   * <code>string reason = 4 [json_name = "reason"];</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    java.lang.Object ref = reason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, actorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filterId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, filterId_);
    }
    if (detectedTimestamp_ != 0L) {
      output.writeInt64(3, detectedTimestamp_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reason_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, reason_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, actorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filterId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, filterId_);
    }
    if (detectedTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, detectedTimestamp_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reason_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, reason_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.akto.proto.smart_event.v1.SmartEvent)) {
      return super.equals(obj);
    }
    io.akto.proto.smart_event.v1.SmartEvent other = (io.akto.proto.smart_event.v1.SmartEvent) obj;

    if (!getActorId()
        .equals(other.getActorId())) return false;
    if (!getFilterId()
        .equals(other.getFilterId())) return false;
    if (getDetectedTimestamp()
        != other.getDetectedTimestamp()) return false;
    if (!getReason()
        .equals(other.getReason())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getActorId().hashCode();
    hash = (37 * hash) + FILTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFilterId().hashCode();
    hash = (37 * hash) + DETECTED_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDetectedTimestamp());
    hash = (37 * hash) + REASON_FIELD_NUMBER;
    hash = (53 * hash) + getReason().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.akto.proto.smart_event.v1.SmartEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.akto.proto.smart_event.v1.SmartEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.akto.proto.smart_event.v1.SmartEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.akto.proto.smart_event.v1.SmartEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smart_event.v1.SmartEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smart_event.v1.SmartEvent)
      io.akto.proto.smart_event.v1.SmartEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.akto.proto.smart_event.v1.SmartEventProto.internal_static_smart_event_v1_SmartEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.akto.proto.smart_event.v1.SmartEventProto.internal_static_smart_event_v1_SmartEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.akto.proto.smart_event.v1.SmartEvent.class, io.akto.proto.smart_event.v1.SmartEvent.Builder.class);
    }

    // Construct using io.akto.proto.smart_event.v1.SmartEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      actorId_ = "";
      filterId_ = "";
      detectedTimestamp_ = 0L;
      reason_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.akto.proto.smart_event.v1.SmartEventProto.internal_static_smart_event_v1_SmartEvent_descriptor;
    }

    @java.lang.Override
    public io.akto.proto.smart_event.v1.SmartEvent getDefaultInstanceForType() {
      return io.akto.proto.smart_event.v1.SmartEvent.getDefaultInstance();
    }

    @java.lang.Override
    public io.akto.proto.smart_event.v1.SmartEvent build() {
      io.akto.proto.smart_event.v1.SmartEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.akto.proto.smart_event.v1.SmartEvent buildPartial() {
      io.akto.proto.smart_event.v1.SmartEvent result = new io.akto.proto.smart_event.v1.SmartEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.akto.proto.smart_event.v1.SmartEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.actorId_ = actorId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.filterId_ = filterId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.detectedTimestamp_ = detectedTimestamp_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.reason_ = reason_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.akto.proto.smart_event.v1.SmartEvent) {
        return mergeFrom((io.akto.proto.smart_event.v1.SmartEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.akto.proto.smart_event.v1.SmartEvent other) {
      if (other == io.akto.proto.smart_event.v1.SmartEvent.getDefaultInstance()) return this;
      if (!other.getActorId().isEmpty()) {
        actorId_ = other.actorId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFilterId().isEmpty()) {
        filterId_ = other.filterId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getDetectedTimestamp() != 0L) {
        setDetectedTimestamp(other.getDetectedTimestamp());
      }
      if (!other.getReason().isEmpty()) {
        reason_ = other.reason_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              actorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              filterId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              detectedTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              reason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object actorId_ = "";
    /**
     * <code>string actor_id = 1 [json_name = "actorId"];</code>
     * @return The actorId.
     */
    public java.lang.String getActorId() {
      java.lang.Object ref = actorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string actor_id = 1 [json_name = "actorId"];</code>
     * @return The bytes for actorId.
     */
    public com.google.protobuf.ByteString
        getActorIdBytes() {
      java.lang.Object ref = actorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string actor_id = 1 [json_name = "actorId"];</code>
     * @param value The actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string actor_id = 1 [json_name = "actorId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActorId() {
      actorId_ = getDefaultInstance().getActorId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string actor_id = 1 [json_name = "actorId"];</code>
     * @param value The bytes for actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object filterId_ = "";
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @return The filterId.
     */
    public java.lang.String getFilterId() {
      java.lang.Object ref = filterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @return The bytes for filterId.
     */
    public com.google.protobuf.ByteString
        getFilterIdBytes() {
      java.lang.Object ref = filterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @param value The filterId to set.
     * @return This builder for chaining.
     */
    public Builder setFilterId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      filterId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFilterId() {
      filterId_ = getDefaultInstance().getFilterId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string filter_id = 2 [json_name = "filterId"];</code>
     * @param value The bytes for filterId to set.
     * @return This builder for chaining.
     */
    public Builder setFilterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      filterId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long detectedTimestamp_ ;
    /**
     * <code>int64 detected_timestamp = 3 [json_name = "detectedTimestamp"];</code>
     * @return The detectedTimestamp.
     */
    @java.lang.Override
    public long getDetectedTimestamp() {
      return detectedTimestamp_;
    }
    /**
     * <code>int64 detected_timestamp = 3 [json_name = "detectedTimestamp"];</code>
     * @param value The detectedTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setDetectedTimestamp(long value) {

      detectedTimestamp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 detected_timestamp = 3 [json_name = "detectedTimestamp"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDetectedTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      detectedTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object reason_ = "";
    /**
     * <code>string reason = 4 [json_name = "reason"];</code>
     * @return The reason.
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reason = 4 [json_name = "reason"];</code>
     * @return The bytes for reason.
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reason = 4 [json_name = "reason"];</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reason_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string reason = 4 [json_name = "reason"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      reason_ = getDefaultInstance().getReason();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string reason = 4 [json_name = "reason"];</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reason_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:smart_event.v1.SmartEvent)
  }

  // @@protoc_insertion_point(class_scope:smart_event.v1.SmartEvent)
  private static final io.akto.proto.smart_event.v1.SmartEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.akto.proto.smart_event.v1.SmartEvent();
  }

  public static io.akto.proto.smart_event.v1.SmartEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SmartEvent>
      PARSER = new com.google.protobuf.AbstractParser<SmartEvent>() {
    @java.lang.Override
    public SmartEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SmartEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SmartEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.akto.proto.smart_event.v1.SmartEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

