package com.akto.dto;

import java.util.List;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.bson.codecs.pojo.annotations.BsonId;
import org.bson.codecs.pojo.annotations.BsonIgnore;
import org.bson.codecs.pojo.annotations.BsonProperty;
import org.bson.types.ObjectId;

@Getter
@Setter
@NoArgsConstructor
public class EndpointRemoteCommand {

    /**
     * MongoDB _id — always present; auto-generated by the dashboard.
     * This is the canonical document identifier used in all filter operations.
     */
    @BsonId
    private ObjectId objectId;

    /**
     * Legacy string id field — absent in documents created by the dashboard.
     * Getter is suppressed so the manual getId() below is used everywhere.
     */
    public static final String ID = "id";
    @Getter(AccessLevel.NONE)
    @BsonProperty("id")
    private String id;

    /** Returns the ObjectId hex string as the canonical id; falls back to the string id field. */
    public String getId() {
        return objectId != null ? objectId.toHexString() : id;
    }

    public static final String COMMAND = "command";
    private String command;

    public static final String ARGS = "args";
    private List<String> args;

    public static final String TIMEOUT_SEC = "timeoutSec";
    private int timeoutSec;

    public static final String EXPIRY_SECONDS = "expirySeconds";
    private int expirySeconds = 3600;

    public static final String TARGET_TYPE = "targetType";
    private TargetType targetType;

    public static final String TARGET_DEVICE_IDS = "targetDeviceIds";
    private List<String> targetDeviceIds;

    public static final String STATUS = "status";
    private Status status;

    public static final String CREATED_AT = "createdAt";
    private long createdAt;

    /** Pre-computed by the dashboard: createdAt + expirySeconds * 1000 (milliseconds). */
    public static final String EXPIRES_AT = "expiresAt";
    private long expiresAt;

    public static final String CREATED_BY = "createdBy";
    private String createdBy;

    public static final String UPDATED_AT = "updatedAt";
    private long updatedAt;

    /** Populated server-side for dashboard list response; not stored in MongoDB. */
    @BsonIgnore
    private ExecutionSummary executionSummary;

    public enum Status {
        ACTIVE, CANCELLED, EXPIRED
    }

    public enum TargetType {
        ALL, SELECTED
    }

    @Getter
    @Setter
    @NoArgsConstructor
    public static class ExecutionSummary {
        private int total;
        private int pending;
        private int running;
        private int completed;
        private int failed;
    }
}
