package com.akto.notifications.slack;

public enum SlackAlertType {
    ACCOUNT_LIMIT_WARNING_ALERT,
    API_TEST_STATUS_ALERT,
    NEW_SERVICE_STATUS_ALERT,
    NEW_USER_JOINING_ALERT,
    DAILY_API_INVENTORY_SUMMARY_ALERT
}
