# Auto-generated wrapper for Akto guardrails hook
# Generated by MCP Endpoint Shield installer

$env:MODE = "atlas"
$env:AKTO_DATA_INGESTION_URL = "{{AKTO_DATA_INGESTION_URL}}"
$env:AKTO_SYNC_MODE = "true"
$env:AKTO_TIMEOUT = "5"
$env:AKTO_CONNECTOR = "gemini_cli"
$env:AKTO_CONNECTOR_VALUE = "geminicli"
$env:CONTEXT_SOURCE = "ENDPOINT"
$env:DEVICE_ID = "{{DEVICE_ID}}"
$env:LOG_LEVEL = "INFO"
$env:LOG_PAYLOADS = "false"

# Execute Python hook script
python "$env:USERPROFILE\.gemini\hooks\akto-validate-pre-tool.py" @args
exit $LASTEXITCODE
