#!/usr/bin/env bash
# install-shell-hooks.sh - install the Akto github-cli SHELL hooks (no python, no jq).
#
# Supports two install modes:
#   --global     Install hooks globally to ~/.github/hooks/ (default)
#   --project    Install hooks to ./.github/hooks/ (current project dir)
#
# Deploys bash hooks + shared lib, generates runtime-detecting wrappers,
# and writes hooks.json (project hooks format).
#
# Usage:
#   install-shell-hooks.sh [--ingestion-url URL] [--api-token TOKEN] [--device-id ID]
#                          [--global | --project] [--home DIR] [--src DIR]
set -eu

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INGESTION_URL="${AKTO_DATA_INGESTION_URL:-}"
API_TOKEN="${AKTO_API_TOKEN:-}"
DEVICE_ID="${DEVICE_ID:-}"
TARGET_HOME="$HOME"
SRC_BASH="$SRC_DIR/bash"
INSTALL_MODE="global"   # "global" or "project"

while [ $# -gt 0 ]; do
  case "$1" in
    --ingestion-url) INGESTION_URL="$2"; shift 2;;
    --api-token)     API_TOKEN="$2"; shift 2;;
    --device-id)     DEVICE_ID="$2"; shift 2;;
    --global)        INSTALL_MODE="global"; shift;;
    --project)       INSTALL_MODE="project"; shift;;
    --home)          TARGET_HOME="$2"; shift 2;;
    --src)           SRC_BASH="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

if [ "$INSTALL_MODE" = "project" ]; then
  HOOKS_DIR="$(pwd)/.github/hooks"
  SETTINGS="$(pwd)/.github/hooks.json"
else
  HOOKS_DIR="$TARGET_HOME/.github/hooks"
  SETTINGS="$TARGET_HOME/.github/hooks.json"
fi

log() { echo "[Akto github shell-hooks] $1"; }

# device label
if [ -z "$DEVICE_ID" ]; then
  _name="$(scutil --get ComputerName 2>/dev/null | tr ' ' '-')" || true
  [ -z "$_name" ] && _name="$(hostname 2>/dev/null | sed 's/\.local$//' | tr ' ' '-')"
  _mid=""
  if command -v ioreg >/dev/null 2>&1; then
    _mid="$(ioreg -rd1 -c IOPlatformExpertDevice 2>/dev/null | grep IOPlatformUUID | awk -F'"' '{print $4}' | tr -d '-' | tr '[:upper:]' '[:lower:]')" || true
  fi
  [ -z "$_mid" ] && [ -r /etc/machine-id ] && _mid="$(tr -d '-' < /etc/machine-id)"
  DEVICE_ID="${_name}-${_mid:0:8}"
fi

mkdir -p "$HOOKS_DIR"
log "Hooks dir: $HOOKS_DIR (mode: $INSTALL_MODE)"

# 1) copy shell hooks + shared lib
for f in akto_common.sh akto-validate-prompt.sh akto-validate-pre-tool.sh \
         akto-validate-post-tool.sh akto-hooks.sh; do
  cp "$SRC_BASH/$f" "$HOOKS_DIR/$f"
  chmod +x "$HOOKS_DIR/$f"
done
log "Installed bash hooks + akto_common.sh"

# 2) generate runtime-detecting wrappers
#    $1=hook basename (prompt|pre-tool|post-tool)
make_wrapper() {
  local name="$1"
  local wf="$HOOKS_DIR/akto-validate-${name}-wrapper.sh"
  cat > "$wf" <<EOF
#!/bin/bash
# Auto-generated by Akto github shell-hooks installer (runtime-detecting)
export MODE="atlas"
export AKTO_DATA_INGESTION_URL="$INGESTION_URL"
export AKTO_API_TOKEN="$API_TOKEN"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="copilot_cli"
export CONTEXT_SOURCE="ENDPOINT"
export DEVICE_ID="$DEVICE_ID"
export LOG_LEVEL="INFO"
export LOG_PAYLOADS="false"

HOOKS_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
if command -v python3 >/dev/null 2>&1 && [ "\${AKTO_HOOK_RUNTIME:-}" != "shell" ] && [ -f "\$HOOKS_DIR/akto-validate-${name}.py" ]; then
  exec python3 "\$HOOKS_DIR/akto-validate-${name}.py" "\$@"
else
  exec bash "\$HOOKS_DIR/akto-validate-${name}.sh" "\$@"
fi
EOF
  chmod +x "$wf"
}

make_wrapper prompt
make_wrapper pre-tool
make_wrapper post-tool
log "Generated runtime-detecting wrappers"

# observability wrapper
cat > "$HOOKS_DIR/akto-hook-wrapper.sh" <<EOF
#!/bin/bash
# Auto-generated by Akto github shell-hooks installer (runtime-detecting)
export MODE="atlas"
export AKTO_DATA_INGESTION_URL="$INGESTION_URL"
export AKTO_API_TOKEN="$API_TOKEN"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="vscode"
export CONTEXT_SOURCE="ENDPOINT"
export DEVICE_ID="$DEVICE_ID"
HOOKS_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
HOOK_EVENT="\$2"; [ -z "\$HOOK_EVENT" ] && HOOK_EVENT="\$1"
if command -v python3 >/dev/null 2>&1 && [ "\${AKTO_HOOK_RUNTIME:-}" != "shell" ] && [ -f "\$HOOKS_DIR/akto-hooks.py" ]; then
  exec python3 "\$HOOKS_DIR/\$1" "\${@:2}"
else
  exec bash "\$HOOKS_DIR/akto-hooks.sh" "\$HOOK_EVENT"
fi
EOF
chmod +x "$HOOKS_DIR/akto-hook-wrapper.sh"
log "Generated observability wrapper"

# 3) write hooks.json
P="$HOOKS_DIR/akto-validate-prompt-wrapper.sh"
PRE="$HOOKS_DIR/akto-validate-pre-tool-wrapper.sh"
POST="$HOOKS_DIR/akto-validate-post-tool-wrapper.sh"
OBS="$HOOKS_DIR/akto-hook-wrapper.sh"

[ -f "$SETTINGS" ] && cp "$SETTINGS" "$SETTINGS.backup.$(date +%s)" && log "Backed up existing hooks.json"
mkdir -p "$(dirname "$SETTINGS")"

cat > "$SETTINGS" <<EOF
{
  "version": 1,
  "hooks": {
    "userPromptSubmitted": [
      {
        "type": "command",
        "bash": "bash $P",
        "comment": "Validate prompts against Akto Guardrails (monitoring only - cannot block per GitHub limitation)",
        "timeoutSec": 30
      }
    ],
    "preToolUse": [
      {
        "type": "command",
        "bash": "bash $PRE",
        "comment": "Validate and block tool execution based on Akto Guardrails policies",
        "timeoutSec": 30
      }
    ],
    "postToolUse": [
      {
        "type": "command",
        "bash": "bash $POST",
        "comment": "Ingest tool execution results to Akto for monitoring and analytics",
        "timeoutSec": 30
      }
    ],
    "_disabled_SessionStart": [
      {
        "type": "command",
        "bash": "bash $OBS akto-hooks.py SessionStart",
        "comment": "DISABLED: not supported by current GitHub Copilot hook contract. Rename key to SessionStart to enable.",
        "timeoutSec": 10
      }
    ]
  }
}
EOF
log "Wrote hooks.json"
log "Done. Runtime: shell when python3 absent (or AKTO_HOOK_RUNTIME=shell)."
