export const labelMap = {
  "API Security": {
    "API Security Posture": "API Security Posture",
    "API Discovery": "API Discovery",
    "API collections": "API Collections",
    "API Collections": "API Collections",
    "API Collection Coverage": "API Collection Coverage",
    "API collection name": "API Collection Name",
    "API Testing": "API Security Testing",
    "Threat Detection": "API Threat Detection",
    "Total APIs": "Total APIs",
    "Critical APIs": "Critical APIs",
    "Tested APIs (Coverage)": "Tested APIs (Coverage)",
    "Sensitive in response APIs": "Sensitive in response APIs",
    "Untracked APIs": "Untracked APIs",
    "Total endpoints": "Total endpoints",
    "Test your APIs": "Test your APIs",
    "API Security": "API Security",
    "API endpoint": "API endpoint",
    "API endpoints": "API endpoints",
    "API details": "API details",
    "New endpoints": "New endpoints",
    "New sensitive endpoints": "New sensitive endpoints",
    "APIs Affected": "APIs Affected",
    "APIs": "APIs",
    "API": "API",
    "API response": "API response",
    "API request": "API request",
    "API Risk Score": "API Risk Score",
    "Endpoint": "Endpoint",
    "API changes": "API changes",
    "APIs Tested": "APIs Tested",
    "APIs with most open issues": "APIs with most open issues"
  },
  "MCP Security": {
    "API Security Posture": "MCP Security Posture",
    "API Discovery": "MCP Discovery",
    "API collections": "MCP Collections",
    "API Collections": "MCP Collections",
    "API Collection Coverage": "MCP Collection Coverage",
    "API collection name": "MCP Collection Name",
    "API Testing": "MCP Red Teaming",
    "Threat Detection": "MCP Protection",
    "Total APIs": "Total tools",
    "Critical APIs": "Critical tools",
    "Tested APIs (Coverage)": "Tested tools (Coverage)",
    "Sensitive in response APIs": "Sensitive in Response",
    "Untracked APIs": "Untracked tools",
    "Total endpoints": "Total tools",
    "Test your APIs": "Test your MCPs",
    "API Security": "MCP Security",
    "API endpoint": "MCP component",
    "API endpoints": "MCP components",
    "API details": "Tool details",
    "New endpoints": "New mcp components",
    "New sensitive endpoints": "New sensitive mcp components",
    "APIs Affected": "MCP components Affected",
    "APIs": "MCP components",
    "API": "MCP component",
    "API response": "Tool response",
    "API request": "Tool request",
    "API Risk Score": "MCP components Risk Score",
    "Endpoint": "MCP component",
    "Threat Policy": "Guardrails Policy",
    "API Threat Activity": "MCP Threat Activity",
    "API changes": "Recent MCP components",
    "APIs Tested": "Tools tested",
    "APIs with most open issues": "MCP components with most open issues"
  },
  "Gen AI": {
    "API Security Posture": "AI Agent Security Posture",
    "API Discovery": "AI Agent Discovery",
    "API collections": "AI Agent Collections",
    "API Collections": "AI Agent Collections",
    "API Collection Coverage": "AI Agent Collection Coverage",
    "API collection name": "AI Agent Collection Name",
    "API Testing": "AI Agent Red Teaming",
    "Threat Detection": "AI Agent Protection",
    "Total APIs": "Total AI Agents",
    "Critical APIs": "Critical AI Agents",
    "Tested APIs (Coverage)": "Tested AI Agents (Coverage)",
    "Sensitive in response APIs": "Sensitive in response AI Agents",
    "Untracked APIs": "Untracked AI Agents",
    "Total endpoints": "Total AI Agent components",
    "Test your APIs": "Test your API Agents",
    "API Security": "AI Security",
    "API endpoint": "AI Agent component",
    "API endpoints": "AI Agent components",
    "API details": "AI Agent details",
    "New endpoints": "New AI Agent components",
    "New sensitive endpoints": "New sensitive AI Agent components",
    "APIs Affected": "AI Agent components Affected",
    "APIs": "AI Agent components",
    "API": "AI Agent component",
    "API response": "AI Agent response",
    "API request": "AI Agent request",
    "API Risk Score": "AI Agent Risk Score",
    "Endpoint": "AI Agent component",
    "API changes": "Recent AI Agent components",
    "APIs with most open issues": "AI Agent components with most open issues"
  },
}