export const labelMap = {
  "API Security": {
    "API Security Posture": "API Security Posture",
    "API Discovery": "API Discovery",
    "API collections": "API Collections",
    "API Collection Coverage": "API Collection Coverage",
    "API collection name": "API Collection Name",
    "API Testing": "API Security Testing",
    "Threat Detection": "API Threat Detection",
    "Total APIs": "Total APIs",
    "Critical APIs": "Critical APIs",
    "Tested APIs (Coverage)": "Tested APIs (Coverage)",
    "Sensitive in response APIs": "Sensitive in response APIs",
    "Untracked APIs": "Untracked APIs",
    "Total endpoints": "Total endpoints",
    "Test your APIs": "Test your APIs",
    "API Security": "API Security",
    "API endpoint": "API endpoint",
    "API endpoints": "API endpoints",
    "API details": "API details",
    "New endpoints": "New endpoints",
    "New sensitive endpoints": "New sensitive endpoints",
    "APIs Affected": "APIs Affected",
    "APIs": "APIs",
    "API": "API",
    "API response": "API response",
    "API request": "API request",
    "API Risk Score": "API Risk Score",
    "Endpoint": "Endpoint",
    "API changes": "API changes",
    "APIs Tested": "APIs Tested",
    "APIs with most open issues": "APIs with most open issues", 
    "Api": "Api",
    "Apis": "Apis",
    "API parameter": "API parameter",
    "API parameters": "API parameters",
    "endpoint": "endpoint",
    "endpoints": "endpoints",
    "URLs": "URLs",
    "security testing": "security testing",
    "test results": "test results",
    "tests": "tests",
    "Test result": "Test result",
    "Test results": "Test results",
    "Tests": "Tests",
    "Test": "Test",
    "test coverage": "test coverage",
    "API security tests": "API security tests",
    "Run test": "Run test",
    "run test": "run test",
    "Run Test": "Run Test",
    "Run tests": "Run Tests",
    "Run Tests": "Run Tests",
    "Number of tests": "Number of tests",
    "Continuous Testing": "Continuous testing",
    "More Tests": "Tests",
    "Results": "Results",
    "tested": "tested",
    "Test runs": "Test runs",
    "Test Editor": "Test Editor",
    "test": 'test',
    "Testing": "Testing",
    "Tested": "Tested",
    "API Security testing": "API Security testing",
    "tests selected": "tests selected",
    "testing": "testing",
    "Test library":"Test library",
    "Endpoint Shield": "API Endpoint Shield"
  },
  "DAST": {
    "API Security Posture": "Security Posture",
    "API Discovery": "DAST Discovery",
    "API Collections": "DAST Collections",
    "API collections": "DAST Collections",
    "API Collection Coverage": "DAST Collection Coverage",
    "API collection name": "API Collection Name",
    "API Testing": "Security Testing",
    "Threat Detection": "Threat Detection",
    "Total APIs": "Total APIs",
    "Critical APIs": "Critical APIs",
    "Tested APIs (Coverage)": "Tested APIs (Coverage)",
    "Sensitive in response APIs": "Sensitive in response APIs",
    "Untracked APIs": "Untracked APIs",
    "Total endpoints": "Total endpoints",
    "Test your APIs": "Test your APIs",
    "API Security": "API Security",
    "API endpoint": "API endpoint",
    "API endpoints": "API endpoints",
    "API details": "API details",
    "New endpoints": "New endpoints",
    "New sensitive endpoints": "New sensitive endpoints",
    "APIs Affected": "APIs Affected",
    "APIs": "APIs",
    "API": "API",
    "API response": "API response",
    "API request": "API request",
    "API Risk Score": "API Risk Score",
    "Endpoint": "Endpoint",
    "API changes": "API changes",
    "APIs Tested": "APIs Tested",
    "APIs with most open issues": "APIs with most open issues", 
    "Api": "Api",
    "Apis": "Apis",
    "API parameter": "API parameter",
    "API parameters": "API parameters",
    "endpoint": "endpoint",
    "endpoints": "endpoints",
    "URLs": "URLs",
    "security testing": "security testing",
    "test results": "test results",
    "tests": "tests",
    "Test result": "Test result",
    "Test results": "Test results",
    "Tests": "Tests",
    "Test": "Test",
    "test coverage": "test coverage",
    "API security tests": "API security tests",
    "Run test": "Run test",
    "run test": "run test",
    "Run Test": "Run Test",
    "Run tests": "Run Tests",
    "Run Tests": "Run Tests",
    "Number of tests": "Number of tests",
    "Continuous Testing": "Continuous testing",
    "More Tests": "Tests",
    "Results": "Results",
    "tested": "tested",
    "Test runs": "Test runs",
    "Test Editor": "Test Editor",
    "test": 'test',
    "Testing": "Testing",
    "Tested": "Tested",
    "API Security testing": "API Security testing",
    "tests selected": "tests selected",
    "testing": "testing",
    "Test library":"Test library",
    "Endpoint Shield": "Endpoint Shield"
  },
  "MCP Security": {
    "API Security Posture": "MCP Security Posture",
    "API Discovery": "MCP Discovery",
    "API collections": "MCP Collections",
    "API Collections": "MCP Collections",
    "API Collection Coverage": "MCP Collection Coverage",
    "API collection name": "MCP Collection Name",
    "API Testing": "MCP Red Teaming",
    "Threat Detection": "MCP Protection",
    "Total APIs": "Total tools",
    "Critical APIs": "Critical tools",
    "Tested APIs (Coverage)": "Tested tools (Coverage)",
    "Sensitive in response APIs": "Sensitive in Response",
    "Untracked APIs": "Untracked tools",
    "Total endpoints": "Total tools",
    "Test your APIs": "Scan your MCPs",
    "API Security": "MCP Security",
    "API endpoint": "MCP component",
    "API endpoints": "MCP components",
    "API details": "Tool details",
    "New endpoints": "New mcp components",
    "New sensitive endpoints": "New sensitive mcp components",
    "APIs Affected": "MCP components Affected",
    "APIs": "MCP components",
    "API": "MCP component",
    "API response": "Tool response",
    "API request": "Tool request",
    "API Risk Score": "MCP components Risk Score",
    "Endpoint": "MCP component",
    "Threat Policies": "Guardrails Policy",
    "API Threat Activity": "MCP Guardrail Activity",
    "API changes": "Recent MCP components",
    "APIs Tested": "Tools tested",
    "APIs with most open issues": "MCP components with most open issues",
    "Api": "MCP component",
    "Apis": "MCP components",
    "API parameter": "MCP tools parameter",
    "API parameters": "MCP tools parameters",
    "endpoint": "MCP component",
    "endpoints": "MCP components",
    "URLs": "MCP components",
    "security testing": "red teaming",
    "test results": "scan results",
    "tests": "scans", 
    "Test result": "Scan result",
    "Test results": "Scan results",
    "Tests": "Scans",
    "Test": "Scan",
    "test coverage": "scan coverage",
    "API security tests": "MCP red teaming scans",
    "Run test": "Run scan",
    "run test": "run scan",
    "Run Test": "Run Scan",
    "Run tests": "Run scans",
    "Run Tests": "Run Scans",
    "Number of tests": "Number of probes",
    "Continuous Testing": "Continuous scanning",
    "More Tests": "Probes",
    "Results": "Probes",  
    "tested": "scanned",
    "Test runs": "Scan runs",
    "Test Editor": "MCP tools Playground",
    "test": 'test',
    "Testing": "Scanning",
    "Tested": "Scanned",
    "API Security testing": "MCP Red teaming",
    "tests selected": "probes selected",
    "testing": "scanning",
    "Test library":"Probe library",
    "Endpoint Shield": "MCP Endpoint Shield",
    "Threat": "Guardrail"
  },
  "Gen AI": {
    "API Security Posture": "AI Agent Security Posture",
    "API Discovery": "AI Agent Discovery",
    "API collections": "AI Agent Collections",
    "API Collections": "AI Agent Collections",
    "API Collection Coverage": "AI Agent Collection Coverage",
    "API collection name": "AI Agent Collection Name",
    "API Testing": "AI Agent Red Teaming",
    "Threat Detection": "AI Agent Protection",
    "Total APIs": "Total AI Agents",
    "Critical APIs": "Critical AI Agents",
    "Tested APIs (Coverage)": "Tested AI Agents (Coverage)",
    "Sensitive in response APIs": "Sensitive in response AI Agents",
    "Untracked APIs": "Untracked AI Agents",
    "Total endpoints": "Total AI Agent components",
    "Test your APIs": "Scan your API Agents",
    "API Security": "AI Security",
    "API endpoint": "AI Agent component",
    "API endpoints": "AI Agent components",
    "API details": "AI Agent details",
    "New endpoints": "New AI Agent components",
    "New sensitive endpoints": "New sensitive AI Agent components",
    "APIs Affected": "AI Agent components Affected",
    "APIs": "AI Agent components",
    "API": "AI Agent component",
    "API response": "AI Agent response",
    "API request": "AI Agent request",
    "API Risk Score": "AI Agent Risk Score",
    "Endpoint": "AI Agent component",
    "API changes": "Recent AI Agent components",
    "APIs with most open issues": "AI Agent components with most open issues",
    "Api": "AI Agent component",
    "Apis": "AI Agent components",
    "API parameter": "AI Agent parameter",
    "API parameters": "AI Agent parameters",
    "endpoint": "AI Agent component",
    "endpoints": "AI Agent components",
    "URLs": "Agent components",
    "security testing": "red teaming",
    "test results": "scan results",
    "tests": "scans",
    "Test result": "Scan result",
    "Test results": "Scan results",
    "Tests": "Scans",
    "Test": "Scan",
    "test coverage": "scan coverage",
    "API security tests": "AI Agent red teaming scans",
    "Run test": "Run scan",
    "run test": "run scan",
    "Run Test": "Run Scan",
    "Run tests": "Run scans",
    "Run Tests": "Run Scans",
    "Number of tests": "Number of probes",
    "Continuous Testing": "Continuous scanning",
    "More Tests": "Probes",
    "Results": "Probes",
    "tested": "scanned",
    "Test runs": "Scan runs",
    "Test Editor": "AI Agent Playground",
    "test": 'scan',
    "Testing": "Scanning",
    "Tested": "Scanned",
    "API Security testing": "AI Agent Red teaming",
    "tests selected": "probes selected",
    "testing": "scanning",
    "Test library":"Probe library",
    "Endpoint Shield": "AI Agent Endpoint Shield"
  },
  "Agentic Security": {
    "API Security Posture": "Agentic Security Posture",
    "API Discovery": "Agentic Discovery",
    "API collections": "Agentic Collections",
    "API Collections": "Agentic Collections",
    "API Collection Coverage": "Agentic Collection Coverage",
    "API collection name": "Agentic Collection Name",
    "API Testing": "Agentic Red Teaming",
    "Threat Detection": "Agentic Guardrails",
    "Total APIs": "Total Agentic Components",
    "Critical APIs": "Critical Agentic Components",
    "Tested APIs (Coverage)": "Tested Agentic Components (Coverage)",
    "Sensitive in response APIs": "Sensitive in Response",
    "Untracked APIs": "Untracked Agentic Components",
    "Total endpoints": "Total Agentic Components",
    "Test your APIs": "Test your Agentic Systems",
    "API Security": "Agentic Security",
    "API endpoint": "Agentic Component",
    "API endpoints": "Agentic Components",
    "API details": "Agentic Component Details",
    "New endpoints": "New Agentic Components",
    "New sensitive endpoints": "New Sensitive Agentic Components",
    "APIs Affected": "Agentic Components Affected",
    "APIs": "Agentic Components",
    "API": "Agentic Component",
    "API response": "Agentic Response",
    "API request": "Agentic Request",
    "API Risk Score": "Agentic Risk Score",
    "Endpoint": "Agentic Component",
    "Threat Policy": "Agentic Guardrails Policy",
    "API Threat Activity": "Agentic Guardrail Activity",
    "API changes": "Recent Agentic Components",
    "APIs Tested": "Agentic Components Tested",
    "APIs with most open issues": "Agentic Components with most open issues",
    "Api": "Agentic Component",
    "Apis": "Agentic Components",
    "API parameter": "Agentic parameter",
    "API parameters": "Agentic Parameters",
    "endpoint": "Agentic component",
    "endpoints": "Agentic components",
    "URLs": "Agentic components",
    "security testing": "red teaming",
    "test results": "scan results",
    "tests": "scans",
    "Test result": "Scan result",
    "Test results": "Scan results",
    "Tests": "Scans",
    "Test": "Scan",
    "test coverage": "scan coverage",
    "API security tests": "Agentic red teaming scans",
    "Run test": "Run scan",
    "run test": "run scan",
    "Run Test": "Run Scan",
    "Run tests": "Run scans",
    "Run Tests": "Run Scans",
    "Number of tests": "Number of probes",
    "Continuous Testing": "Continuous scanning",
    "More Tests": "Probes",
    "Results": "Probes",
    "tested": "scanned",
    "Test runs": "Scan runs",
    "Test Editor": "Agentic Playground",
    "test": 'scan',
    "Testing": "Scanning",
    "Tested": "Scanned",
    "API Security testing": "Agentic Red teaming",
    "tests selected": "probes selected",
    "testing": "scanning",
    "Test library":"Probe library",
    "Endpoint Shield": "Agentic Endpoint Shield",
    "Threat": "Guardrail"
  },
}