#!/usr/bin/env bash
# install-shell-hooks.sh - install the Akto claude-cli SHELL hooks (no python, no jq).
#
# Deploys the bash hooks + shared lib into ~/.claude/hooks, generates
# runtime-detecting wrapper scripts, and wires ~/.claude/settings.json.
#
# Works fully offline from a local checkout (default) or can be adapted to
# download from GitHub. Designed to coexist with the existing Python installer:
# wrappers prefer python3 when present, else run the shell hook. Force shell
# with AKTO_HOOK_RUNTIME=shell.
#
# Usage:
#   install-shell-hooks.sh [--ingestion-url URL] [--device-id ID] [--home DIR] [--src DIR]
set -eu

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INGESTION_URL="${AKTO_DATA_INGESTION_URL:-}"
DEVICE_ID="${DEVICE_ID:-}"
TARGET_HOME="$HOME"
SRC_BASH="$SRC_DIR/bash"

while [ $# -gt 0 ]; do
  case "$1" in
    --ingestion-url) INGESTION_URL="$2"; shift 2;;
    --device-id) DEVICE_ID="$2"; shift 2;;
    --home) TARGET_HOME="$2"; shift 2;;
    --src) SRC_BASH="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

HOOKS_DIR="$TARGET_HOME/.claude/hooks"
SETTINGS="$TARGET_HOME/.claude/settings.json"
log() { echo "[Akto shell-hooks] $1"; }

# device label (hostname-first8 of machine id), mirrors generate_device_label()
if [ -z "$DEVICE_ID" ]; then
  _name="$(scutil --get ComputerName 2>/dev/null | tr ' ' '-')"
  [ -z "$_name" ] && _name="$(hostname 2>/dev/null | sed 's/\.local$//' | tr ' ' '-')"
  _mid=""
  if command -v ioreg >/dev/null 2>&1; then
    _mid="$(ioreg -rd1 -c IOPlatformExpertDevice 2>/dev/null | grep IOPlatformUUID | awk -F'"' '{print $4}' | tr -d '-' | tr '[:upper:]' '[:lower:]')"
  fi
  [ -z "$_mid" ] && [ -r /etc/machine-id ] && _mid="$(tr -d '-' < /etc/machine-id)"
  DEVICE_ID="${_name}-${_mid:0:8}"
fi

mkdir -p "$HOOKS_DIR"
log "Hooks dir: $HOOKS_DIR"

# 1) copy shell hooks + shared lib
for f in akto_common.sh akto-validate-prompt.sh akto-validate-response.sh \
         akto-validate-mcp-request.sh akto-validate-mcp-response.sh akto-hooks.sh; do
  cp "$SRC_BASH/$f" "$HOOKS_DIR/$f"
  chmod +x "$HOOKS_DIR/$f"
done
log "Installed bash hooks + akto_common.sh"

# 2) generate a runtime-detecting wrapper for a validate hook
#    $1=hook basename (prompt|response|mcp-request|mcp-response)  $2=connector  $3=connector_value
make_wrapper() {
  local name="$1" connector="$2" cvalue="$3"
  local wf="$HOOKS_DIR/akto-validate-${name}-wrapper.sh"
  cat > "$wf" <<EOF
#!/bin/bash
# Auto-generated by Akto shell-hooks installer (runtime-detecting)
export MODE="atlas"
export AKTO_DATA_INGESTION_URL="$INGESTION_URL"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="$connector"
export AKTO_CONNECTOR_VALUE="$cvalue"
export CONTEXT_SOURCE="ENDPOINT"
export DEVICE_ID="$DEVICE_ID"
export LOG_LEVEL="INFO"
export LOG_PAYLOADS="false"

HOOKS_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
if command -v python3 >/dev/null 2>&1 && [ "\${AKTO_HOOK_RUNTIME:-}" != "shell" ] && [ -f "\$HOOKS_DIR/akto-validate-${name}.py" ]; then
  exec python3 "\$HOOKS_DIR/akto-validate-${name}.py" "\$@"
else
  exec bash "\$HOOKS_DIR/akto-validate-${name}.sh" "\$@"
fi
EOF
  chmod +x "$wf"
}

make_wrapper prompt        claude_code_cli claudecli
make_wrapper response      claude_code_cli claudecli
make_wrapper mcp-request   claude_code_cli claudecli
make_wrapper mcp-response  claude_code_cli claudecli
log "Generated runtime-detecting wrappers"

# observability wrapper (akto-hook-wrapper.sh <hookName>)
cat > "$HOOKS_DIR/akto-hook-wrapper.sh" <<EOF
#!/bin/bash
# Auto-generated by Akto shell-hooks installer (runtime-detecting)
export MODE="atlas"
export AKTO_DATA_INGESTION_URL="$INGESTION_URL"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="claude"
export CONTEXT_SOURCE="ENDPOINT"
export DEVICE_ID="$DEVICE_ID"
HOOKS_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
HOOK_EVENT="\$2"; [ -z "\$HOOK_EVENT" ] && HOOK_EVENT="\$1"
if command -v python3 >/dev/null 2>&1 && [ "\${AKTO_HOOK_RUNTIME:-}" != "shell" ] && [ -f "\$HOOKS_DIR/akto-hooks.py" ]; then
  exec python3 "\$HOOKS_DIR/\$1" "\${@:2}"
else
  exec bash "\$HOOKS_DIR/akto-hooks.sh" "\$HOOK_EVENT"
fi
EOF
chmod +x "$HOOKS_DIR/akto-hook-wrapper.sh"
log "Generated observability wrapper"

# 3) wire settings.json (prompt+stop+pre/post tool). Pure-bash JSON write; if a
#    settings.json already exists we back it up and write the hooks block.
P="$HOOKS_DIR/akto-validate-prompt-wrapper.sh"
R="$HOOKS_DIR/akto-validate-response-wrapper.sh"
PRE="$HOOKS_DIR/akto-validate-mcp-request-wrapper.sh"
POST="$HOOKS_DIR/akto-validate-mcp-response-wrapper.sh"
[ -f "$SETTINGS" ] && cp "$SETTINGS" "$SETTINGS.backup.$(date +%s)" && log "Backed up existing settings.json"
mkdir -p "$(dirname "$SETTINGS")"
cat > "$SETTINGS" <<EOF
{
  "hooks": {
    "UserPromptSubmit": [ { "hooks": [ { "type": "command", "command": "$P", "timeout": 10 } ] } ],
    "Stop":             [ { "hooks": [ { "type": "command", "command": "$R", "timeout": 10 } ] } ],
    "PreToolUse":       [ { "hooks": [ { "type": "command", "command": "$PRE", "timeout": 10 } ] } ],
    "PostToolUse":      [ { "hooks": [ { "type": "command", "command": "$POST", "timeout": 10 } ] } ]
  }
}
EOF
log "Wrote settings.json"
log "Done. Runtime: shell when python3 absent (or AKTO_HOOK_RUNTIME=shell)."
