const GUARDRAIL_PRESETS = [
    {
        key: "GDPR",
        label: "GDPR Compliance",
        data: {
            name: "GDPR Compliance",
            description: "Detects personal and sensitive data defined under GDPR within AI prompts and responses, helping identify privacy risks and prevent unintended data exposure.",
            severity: "HIGH",
            behaviour: "block",
            blockedMessage: "This action has been blocked by Akto Policy for GDPR compliance.",
            active: true,
            applyOnRequest: true,
            applyOnResponse: true,
            applyToAllServers: true,
            blockPersonalAccounts: false,
            blockedHosts: [],
            piiTypes: [
                { type: "email", behavior: "block", minMatchCount: 1 },
                { type: "address", behavior: "block", minMatchCount: 1 },
                { type: "credit_card", behavior: "block", minMatchCount: 1 },
                { type: "uuid", behavior: "block", minMatchCount: 1 },
                { type: "ip_address", behavior: "block", minMatchCount: 1 },
                { type: "phone_number", behavior: "block", minMatchCount: 1 },
                { type: "ssn", behavior: "block", minMatchCount: 1 },
                { type: "userid", behavior: "block", minMatchCount: 1 },
            ],
            anonymizeDetection: { enabled: true, confidenceScore: 0.6 },
            secretsDetection: { enabled: true, confidenceScore: 0.7 },
            banCodeDetection: { enabled: false, confidenceScore: 0.7 },
            basePromptRule: { enabled: false, confidenceScore: 0.5 },
            gibberishDetection: { enabled: false, confidenceScore: 0.7 },
            sentimentDetection: { enabled: false, confidenceScore: 0.7 },
            tokenLimitDetection: { enabled: false, confidenceScore: 0.7 },
            llmRule: { enabled: false, confidenceScore: 0.5, userPrompt: "" },
            contentFiltering: {
                promptAttacks: { level: "HIGH" },
                code: null,
                harmfulCategories: null,
            },
            regexPatterns: [],
            regexPatternsV2: [],
            deniedTopics: [
                {
                    topic: "Medical Information",
                    description: "Health records, diagnoses, treatments, prescriptions, medical conditions, or healthcare-related personal information.",
                    samplePhrases: ["Diagnose my symptoms", "Medical report", "Patient history", "Prescription records", "Healthcare data"],
                },
                {
                    topic: "Financial Information",
                    description: "Financial records, salary information, investments, transactions, banking details, or economic status information.",
                    samplePhrases: ["salary information", "bank statement", "investment portfolio", "financial transaction", "account balance"],
                },
                {
                    topic: "Geolocation Information",
                    description: "Exact location information, GPS coordinates, travel history, residence locations, workplace locations, or real-time location data.",
                    samplePhrases: ["GPS coordinates", "current location", "travel history", "home location", "location tracking"],
                },
                {
                    topic: "Special Category Personal Data",
                    description: "These are GDPR Special Category Data, highly sensitive PII. Processing them is prohibited unless a specific legal exception applies, due to the significant risk of discrimination and harm.",
                    samplePhrases: ["political affiliation and voting preferences", "religious beliefs and faith background", "racial or ethnic background", "trade union membership and activities", "personal relationships"],
                },
            ],
        },
    },
    {
        key: "EU_AI_ACT",
        label: "EU AI Act Guardrail",
        data: {
            name: "EU AI Act Guardrail",
            description: "This guardrail detects and blocks prompt patterns associated with AI practices that are prohibited, restricted, or considered high-risk under the EU AI Act",
            severity: "HIGH",
            behaviour: "block",
            blockedMessage: "This action was blocked by Akto - EU AI Act Guardrail",
            active: false,
            applyOnRequest: false,
            applyOnResponse: false,
            applyToAllServers: true,
            blockPersonalAccounts: false,
            blockedHosts: [],
            piiTypes: [
                { type: "email", behavior: "block", minMatchCount: 1 },
                { type: "phone_number", behavior: "block", minMatchCount: 1 },
                { type: "address", behavior: "block", minMatchCount: 1 },
                { type: "ip_address", behavior: "block", minMatchCount: 1 },
                { type: "credit_card", behavior: "block", minMatchCount: 1 },
                { type: "uuid", behavior: "block", minMatchCount: 1 },
                { type: "userid", behavior: "block", minMatchCount: 1 },
            ],
            anonymizeDetection: { enabled: true, confidenceScore: 0.7 },
            secretsDetection: { enabled: true, confidenceScore: 0.7 },
            banCodeDetection: { enabled: false, confidenceScore: 0.7 },
            basePromptRule: { enabled: false, confidenceScore: 0.5 },
            gibberishDetection: { enabled: false, confidenceScore: 0.7 },
            sentimentDetection: { enabled: false, confidenceScore: 0.7 },
            tokenLimitDetection: { enabled: false, confidenceScore: 0.7 },
            llmRule: { enabled: false, confidenceScore: 0.5, userPrompt: "" },
            contentFiltering: {
                promptAttacks: { level: "HIGH" },
                code: null,
                harmfulCategories: null,
            },
            regexPatterns: [],
            regexPatternsV2: [],
            deniedTopics: [
                {
                    topic: "Social Scoring",
                    description: "Requests that evaluate, rank, score, or classify individuals based on behavior, characteristics, reputation, or predicted traits.",
                    samplePhrases: ["assign a trustworthiness score to citizens", "rank employees based on personal behavior", "create a social credit score", "score users based on online activity", "classify people by reputation level"],
                },
                {
                    topic: "Biometric Categorization",
                    description: "Requests that classify or infer personal characteristics from biometric data such as faces, voices, fingerprints, or other biological identifiers.",
                    samplePhrases: ["determine ethnicity from a face", "infer religion from facial features", "classify race using photographs", "identify sexual orientation from voice samples", "categorize people using biometric traits"],
                },
                {
                    topic: "Emotion Recognition",
                    description: "Requests that detect, infer, or monitor emotions from facial expressions, voice patterns, behavior, or biometric signals.",
                    samplePhrases: ["detect employee emotions from webcam footage", "determine student stress levels from video", "infer emotional state from voice recordings", "monitor worker happiness during meetings", "classify customer emotions automatically"],
                },
                {
                    topic: "Sensitive Attribute Profiling",
                    description: "Requests that infer, predict, analyze, or profile protected personal characteristics such as political opinions, religion, ethnicity, sexual orientation, or similar sensitive attributes.",
                    samplePhrases: ["predict political affiliation from social media", "determine religious beliefs from online activity", "infer sexual orientation from user behavior", "estimate ethnic background from profile data", "classify people by sensitive personal attributes"],
                },
                {
                    topic: "High-Risk Automated Decision Making",
                    description: "Requests involving fully automated decisions that significantly impact an individual's employment, education, financial services, insurance, housing, or access to essential services.",
                    samplePhrases: ["automatically reject job applicants", "determine loan approvals without human review", "rank university applicants automatically", "decide insurance eligibility using AI", "automate employee promotion decisions"],
                },
            ],
        },
    },
    {
        key: "HIPAA",
        label: "HIPAA",
        data: {
            name: "HIPAA",
            description: "Detects and restricts healthcare-related protected health information (PHI) in AI prompts and responses.",
            severity: "HIGH",
            behaviour: "block",
            blockedMessage: "This action blocked by Akto Policy - HIPAA",
            active: false,
            applyOnRequest: false,
            applyOnResponse: false,
            applyToAllServers: true,
            blockPersonalAccounts: false,
            blockedHosts: [],
            piiTypes: [
                { type: "email", behavior: "block", minMatchCount: 1 },
                { type: "ssn", behavior: "block", minMatchCount: 1 },
                { type: "address", behavior: "block", minMatchCount: 1 },
                { type: "credit_card", behavior: "block", minMatchCount: 1 },
                { type: "uuid", behavior: "block", minMatchCount: 1 },
                { type: "ip_address", behavior: "block", minMatchCount: 1 },
                { type: "phone_number", behavior: "block", minMatchCount: 1 },
                { type: "userid", behavior: "block", minMatchCount: 1 },
            ],
            anonymizeDetection: { enabled: true, confidenceScore: 0.7 },
            secretsDetection: { enabled: true, confidenceScore: 0.7 },
            banCodeDetection: { enabled: false, confidenceScore: 0.7 },
            basePromptRule: { enabled: false, confidenceScore: 0.5 },
            gibberishDetection: { enabled: false, confidenceScore: 0.7 },
            sentimentDetection: { enabled: false, confidenceScore: 0.7 },
            tokenLimitDetection: { enabled: false, confidenceScore: 0.7 },
            llmRule: { enabled: false, confidenceScore: 0.5, userPrompt: "" },
            contentFiltering: {
                promptAttacks: { level: "HIGH" },
                code: null,
                harmfulCategories: null,
            },
            regexPatterns: [],
            regexPatternsV2: [],
            deniedTopics: [
                {
                    topic: "Patient Records",
                    description: "Requests seeking access to, disclosure of, retrieval of, or analysis of identifiable patient records or healthcare records.",
                    samplePhrases: ["Show patient records", "Retrieve medical chart", "List patient details", "Access patient history", "Export patient database"],
                },
                {
                    topic: "Medical History",
                    description: "Requests involving disclosure of an individual's diagnoses, treatments, procedures, laboratory results, or historical medical information.",
                    samplePhrases: ["Show medical history", "Reveal diagnosis information", "Display treatment history", "Show laboratory results", "Access health records"],
                },
                {
                    topic: "Prescription Information",
                    description: "Requests involving medications, prescriptions, prescription history, dosage information, or pharmacy records tied to identifiable individuals.",
                    samplePhrases: ["Show prescription records", "Retrieve medication history", "Display pharmacy information", "List prescribed drugs", "Reveal medication details"],
                },
                {
                    topic: "Insurance and Billing Records",
                    description: "Requests involving healthcare insurance information, claims, billing records, reimbursement data, or patient financial healthcare records.",
                    samplePhrases: ["Show insurance claims", "Retrieve billing records", "Display patient insurance information", "Access healthcare payment history", "Reveal reimbursement details"],
                },
            ],
        },
    },
    {
        key: "PCI_DSS",
        label: "PCI DSS Guardrail",
        data: {
            name: "PCI DSS Guardrail",
            description: "Detects payment card information, payment credentials, and sensitive authentication data in AI prompts and responses to help reduce the risk of exposing cardholder information.",
            severity: "HIGH",
            behaviour: "block",
            blockedMessage: "This action was blocked by Akto Policy - PCI DSS",
            active: false,
            applyOnRequest: false,
            applyOnResponse: false,
            applyToAllServers: true,
            blockPersonalAccounts: false,
            blockedHosts: [],
            piiTypes: [
                { type: "credit_card", behavior: "block", minMatchCount: 1 },
                { type: "credit_card_cap", behavior: "block", minMatchCount: 1 },
                { type: "email", behavior: "block", minMatchCount: 1 },
                { type: "phone_number", behavior: "block", minMatchCount: 1 },
                { type: "address", behavior: "block", minMatchCount: 1 },
            ],
            anonymizeDetection: { enabled: true, confidenceScore: 0.7 },
            secretsDetection: { enabled: true, confidenceScore: 0.5 },
            banCodeDetection: { enabled: false, confidenceScore: 0.7 },
            basePromptRule: { enabled: false, confidenceScore: 0.5 },
            gibberishDetection: { enabled: false, confidenceScore: 0.7 },
            sentimentDetection: { enabled: false, confidenceScore: 0.7 },
            tokenLimitDetection: { enabled: false, confidenceScore: 0.7 },
            llmRule: { enabled: false, confidenceScore: 0.5, userPrompt: "" },
            contentFiltering: {
                promptAttacks: { level: "HIGH" },
                code: null,
                harmfulCategories: null,
            },
            regexPatterns: [],
            regexPatternsV2: [],
            deniedTopics: [
                {
                    topic: "Payment Card Information",
                    description: "Requests involving payment card numbers, cardholder data, card verification values, expiration dates, or payment credentials.",
                    samplePhrases: ["Show customer credit card numbers", "Retrieve stored card data", "Display payment card details", "Export payment records", "Reveal cardholder information"],
                },
                {
                    topic: "Payment Authentication Data",
                    description: "Requests involving authentication data used during payment processing, including CVVs, security codes, PINs, or payment verification information.",
                    samplePhrases: ["Show CVV values", "Reveal security codes", "Retrieve payment PINs", "Display card verification data"],
                },
                {
                    topic: "Customer Payment Records",
                    description: "Requests involving customer transaction histories, payment records, billing information, or financial payment data.",
                    samplePhrases: ["Show payment history", "Retrieve transaction records", "Display billing information", "Export payment transactions"],
                },
            ],
        },
    },
    {
        key: "SOC2",
        label: "SOC 2 Compliance",
        data: {
            name: "SOC 2 Compliance",
            description: "Enforces SOC 2 Trust Services Criteria over AI systems: confidentiality of sensitive data (CC6), resilience to injection (CC6.8/CC7.2), and availability against resource exhaustion (A1).",
            severity: "HIGH",
            behaviour: "block",
            blockedMessage: "This action has been blocked by Akto Policy for SOC 2 compliance.",
            active: true,
            applyOnRequest: true,
            applyOnResponse: true,
            applyToAllServers: true,
            blockPersonalAccounts: false,
            blockedHosts: [],
            piiTypes: [
                { type: "email", behavior: "block", minMatchCount: 1 },
                { type: "ssn", behavior: "block", minMatchCount: 1 },
                { type: "credit_card", behavior: "block", minMatchCount: 1 },
                { type: "address", behavior: "block", minMatchCount: 1 },
                { type: "phone_number", behavior: "block", minMatchCount: 1 },
            ],
            secretsDetection: { enabled: true, confidenceScore: 0.7 },
            tokenLimitDetection: { enabled: true, confidenceScore: 0.7 },
            contentFiltering: {
                promptAttacks: { level: "HIGH" },
                code: { level: "MEDIUM" },
                harmfulCategories: {
                    hate: "HIGH",
                    insults: "HIGH",
                    sexual: "HIGH",
                    violence: "HIGH",
                    misconduct: "HIGH",
                    useForResponses: true,
                },
            },
            regexPatterns: [],
            regexPatternsV2: [],
            deniedTopics: [],
        },
    },
    {
        key: "OWASP_LLM",
        label: "OWASP LLM Top 10",
        data: {
            name: "OWASP LLM Top 10 Compliance",
            description: "Covers the OWASP Top 10 for LLM Applications (2025): prompt injection (LLM01), sensitive disclosure (LLM02), data/model poisoning (LLM04), improper output (LLM05), system prompt leakage (LLM07), and unbounded consumption (LLM10).",
            severity: "HIGH",
            behaviour: "block",
            blockedMessage: "This action has been blocked by Akto Policy for OWASP LLM Top 10 compliance.",
            active: true,
            applyOnRequest: true,
            applyOnResponse: true,
            applyToAllServers: true,
            blockPersonalAccounts: false,
            blockedHosts: [],
            piiTypes: [
                { type: "email", behavior: "block", minMatchCount: 1 },
                { type: "ssn", behavior: "block", minMatchCount: 1 },
                { type: "credit_card", behavior: "block", minMatchCount: 1 },
            ],
            anonymizeDetection: { enabled: true, confidenceScore: 0.6 },
            secretsDetection: { enabled: true, confidenceScore: 0.7 },
            banCodeDetection: { enabled: true, confidenceScore: 0.7 },
            gibberishDetection: { enabled: true, confidenceScore: 0.7 },
            tokenLimitDetection: { enabled: true, confidenceScore: 0.7 },
            basePromptRule: { enabled: true, confidenceScore: 0.5 },
            contentFiltering: {
                promptAttacks: { level: "HIGH" },
                code: { level: "HIGH" },
                harmfulCategories: null,
            },
            regexPatterns: [],
            regexPatternsV2: [],
            deniedTopics: [],
        },
    },
];

export default GUARDRAIL_PRESETS;
