// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: malicious_event/v1/malicious_event.proto
// Protobuf Java Version: 4.28.3

package io.akto.proto.malicious_event.v1;

public final class MaliciousEventProto {
  private MaliciousEventProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      MaliciousEventProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_malicious_event_v1_MaliciousEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_malicious_event_v1_MaliciousEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(malicious_event/v1/malicious_event.pro" +
      "to\022\022malicious_event.v1\"\346\001\n\016MaliciousEven" +
      "t\022\031\n\010actor_id\030\001 \001(\tR\007actorId\022\033\n\tfilter_i" +
      "d\030\002 \001(\tR\010filterId\022\016\n\002ip\030\003 \001(\tR\002ip\022\034\n\ttim" +
      "estamp\030\004 \001(\003R\ttimestamp\022\020\n\003url\030\005 \001(\tR\003ur" +
      "l\022\026\n\006method\030\006 \001(\tR\006method\022*\n\021api_collect" +
      "ion_id\030\007 \001(\tR\017apiCollectionId\022\030\n\007payload" +
      "\030\010 \001(\tR\007payloadB\234\001\n io.akto.proto.malici" +
      "ous_event.v1B\023MaliciousEventProtoP\001\242\002\003MX" +
      "X\252\002\021MaliciousEvent.V1\312\002\021MaliciousEvent\\V" +
      "1\342\002\035MaliciousEvent\\V1\\GPBMetadata\352\002\022Mali" +
      "ciousEvent::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_malicious_event_v1_MaliciousEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_malicious_event_v1_MaliciousEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_malicious_event_v1_MaliciousEvent_descriptor,
        new java.lang.String[] { "ActorId", "FilterId", "Ip", "Timestamp", "Url", "Method", "ApiCollectionId", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
