#!/usr/bin/env bash
# install-shell-hooks.sh - install the Akto gemini-cli SHELL hooks (no python, no jq).
#
# Deploys the bash hooks + shared lib into ~/.gemini/hooks, generates
# runtime-detecting wrapper scripts, and wires ~/.gemini/settings.json.
#
# Works fully offline from a local checkout (default). Designed to coexist with
# the existing Python installer: wrappers prefer python3 when present, else run
# the shell hook. Force shell with AKTO_HOOK_RUNTIME=shell.
#
# Usage:
#   install-shell-hooks.sh [--ingestion-url URL] [--api-token TOKEN] [--device-id ID] [--home DIR] [--src DIR]
set -eu

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INGESTION_URL="${AKTO_DATA_INGESTION_URL:-}"
API_TOKEN="${AKTO_API_TOKEN:-}"
DEVICE_ID="${DEVICE_ID:-}"
TARGET_HOME="$HOME"
SRC_BASH="$SRC_DIR/bash"

while [ $# -gt 0 ]; do
  case "$1" in
    --ingestion-url) INGESTION_URL="$2"; shift 2;;
    --api-token)     API_TOKEN="$2"; shift 2;;
    --device-id)     DEVICE_ID="$2"; shift 2;;
    --home)          TARGET_HOME="$2"; shift 2;;
    --src)           SRC_BASH="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

HOOKS_DIR="$TARGET_HOME/.gemini/hooks"
SETTINGS="$TARGET_HOME/.gemini/settings.json"
log() { echo "[Akto gemini shell-hooks] $1"; }

# device label (hostname-first8 of machine id), mirrors generate_device_label()
if [ -z "$DEVICE_ID" ]; then
  _name="$(scutil --get ComputerName 2>/dev/null | tr ' ' '-')" || true
  [ -z "$_name" ] && _name="$(hostname 2>/dev/null | sed 's/\.local$//' | tr ' ' '-')"
  _mid=""
  if command -v ioreg >/dev/null 2>&1; then
    _mid="$(ioreg -rd1 -c IOPlatformExpertDevice 2>/dev/null | grep IOPlatformUUID | awk -F'"' '{print $4}' | tr -d '-' | tr '[:upper:]' '[:lower:]')" || true
  fi
  [ -z "$_mid" ] && [ -r /etc/machine-id ] && _mid="$(tr -d '-' < /etc/machine-id)"
  DEVICE_ID="${_name}-${_mid:0:8}"
fi

mkdir -p "$HOOKS_DIR"
log "Hooks dir: $HOOKS_DIR"

# 1) copy shell hooks + shared lib
for f in akto_common.sh akto-validate-prompt.sh akto-validate-response.sh \
         akto-validate-pre-tool.sh akto-validate-post-tool.sh akto-hooks.sh; do
  cp "$SRC_BASH/$f" "$HOOKS_DIR/$f"
  chmod +x "$HOOKS_DIR/$f"
done
log "Installed bash hooks + akto_common.sh"

# 2) generate a runtime-detecting wrapper for a validate hook
#    $1=hook basename (prompt|response|pre-tool|post-tool)
make_wrapper() {
  local name="$1"
  local wf="$HOOKS_DIR/akto-validate-${name}-wrapper.sh"
  cat > "$wf" <<EOF
#!/bin/bash
# Auto-generated by Akto gemini shell-hooks installer (runtime-detecting)
export MODE="atlas"
export AKTO_DATA_INGESTION_URL="$INGESTION_URL"
export AKTO_API_TOKEN="$API_TOKEN"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="gemini_cli"
export AKTO_CONNECTOR_VALUE="geminicli"
export CONTEXT_SOURCE="ENDPOINT"
export DEVICE_ID="$DEVICE_ID"
export LOG_LEVEL="INFO"
export LOG_PAYLOADS="false"

HOOKS_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
if command -v python3 >/dev/null 2>&1 && [ "\${AKTO_HOOK_RUNTIME:-}" != "shell" ] && [ -f "\$HOOKS_DIR/akto-validate-${name}.py" ]; then
  exec python3 "\$HOOKS_DIR/akto-validate-${name}.py" "\$@"
else
  exec bash "\$HOOKS_DIR/akto-validate-${name}.sh" "\$@"
fi
EOF
  chmod +x "$wf"
}

make_wrapper prompt
make_wrapper response
make_wrapper pre-tool
make_wrapper post-tool
log "Generated runtime-detecting wrappers"

# observability wrapper
cat > "$HOOKS_DIR/akto-hook-wrapper.sh" <<EOF
#!/bin/bash
# Auto-generated by Akto gemini shell-hooks installer (runtime-detecting)
export MODE="atlas"
export AKTO_DATA_INGESTION_URL="$INGESTION_URL"
export AKTO_API_TOKEN="$API_TOKEN"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="gemini_cli"
export CONTEXT_SOURCE="ENDPOINT"
export DEVICE_ID="$DEVICE_ID"
HOOKS_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
HOOK_EVENT="\$2"; [ -z "\$HOOK_EVENT" ] && HOOK_EVENT="\$1"
if command -v python3 >/dev/null 2>&1 && [ "\${AKTO_HOOK_RUNTIME:-}" != "shell" ] && [ -f "\$HOOKS_DIR/akto-hooks.py" ]; then
  exec python3 "\$HOOKS_DIR/\$1" "\${@:2}"
else
  exec bash "\$HOOKS_DIR/akto-hooks.sh" "\$HOOK_EVENT"
fi
EOF
chmod +x "$HOOKS_DIR/akto-hook-wrapper.sh"
log "Generated observability wrapper"

# 3) wire settings.json (gemini). Back up any existing file.
P="$HOOKS_DIR/akto-validate-prompt-wrapper.sh"
R="$HOOKS_DIR/akto-validate-response-wrapper.sh"
PRE="$HOOKS_DIR/akto-validate-pre-tool-wrapper.sh"
POST="$HOOKS_DIR/akto-validate-post-tool-wrapper.sh"
OBS="$HOOKS_DIR/akto-hook-wrapper.sh"

[ -f "$SETTINGS" ] && cp "$SETTINGS" "$SETTINGS.backup.$(date +%s)" && log "Backed up existing settings.json"
mkdir -p "$(dirname "$SETTINGS")"

cat > "$SETTINGS" <<EOF
{
  "hooks": {
    "BeforeModel": [
      {
        "matcher": "*",
        "hooks": [
          {
            "name": "akto-validate-prompt",
            "type": "command",
            "command": "bash $P",
            "timeout": 10000,
            "description": "Validates prompts against Akto Guardrails before sending to Gemini"
          }
        ]
      }
    ],
    "AfterModel": [
      {
        "matcher": "*",
        "hooks": [
          {
            "name": "akto-validate-response",
            "type": "command",
            "command": "bash $R",
            "timeout": 10000,
            "description": "Sends prompt/response pairs to Akto for ingestion"
          }
        ]
      }
    ],
    "BeforeTool": [
      {
        "matcher": ".*",
        "sequential": true,
        "hooks": [
          {
            "name": "akto-validate-pre-tool",
            "type": "command",
            "command": "bash $PRE",
            "timeout": 10000,
            "description": "Validates tool calls against Akto Guardrails before execution"
          }
        ]
      }
    ],
    "AfterTool": [
      {
        "matcher": ".*",
        "sequential": true,
        "hooks": [
          {
            "name": "akto-validate-post-tool",
            "type": "command",
            "command": "bash $POST",
            "timeout": 10000,
            "description": "Ingests tool execution results to Akto for monitoring and can block malicious results"
          }
        ]
      }
    ],
    "SessionStart": [
      {
        "matcher": "*",
        "hooks": [
          {
            "name": "akto-validate-session-start",
            "type": "command",
            "command": "bash $OBS akto-hooks.py SessionStart",
            "timeout": 10000
          }
        ]
      }
    ],
    "SessionEnd": [
      {
        "matcher": "*",
        "hooks": [
          {
            "name": "akto-validate-session-end",
            "type": "command",
            "command": "bash $OBS akto-hooks.py SessionEnd",
            "timeout": 10000
          }
        ]
      }
    ],
    "BeforeAgent": [
      {
        "matcher": "*",
        "hooks": [
          {
            "name": "akto-validate-before-agent",
            "type": "command",
            "command": "bash $OBS akto-hooks.py BeforeAgent",
            "timeout": 10000
          }
        ]
      }
    ],
    "AfterAgent": [
      {
        "matcher": "*",
        "hooks": [
          {
            "name": "akto-validate-after-agent",
            "type": "command",
            "command": "bash $OBS akto-hooks.py AfterAgent",
            "timeout": 10000
          }
        ]
      }
    ],
    "BeforeToolSelection": [
      {
        "matcher": "*",
        "hooks": [
          {
            "name": "akto-validate-before-tool-selection",
            "type": "command",
            "command": "bash $OBS akto-hooks.py BeforeToolSelection",
            "timeout": 10000
          }
        ]
      }
    ],
    "PreCompress": [
      {
        "matcher": "*",
        "hooks": [
          {
            "name": "akto-validate-pre-compress",
            "type": "command",
            "command": "bash $OBS akto-hooks.py PreCompress",
            "timeout": 10000
          }
        ]
      }
    ],
    "Notification": [
      {
        "matcher": "*",
        "hooks": [
          {
            "name": "akto-validate-notification",
            "type": "command",
            "command": "bash $OBS akto-hooks.py Notification",
            "timeout": 10000
          }
        ]
      }
    ]
  }
}
EOF
log "Wrote settings.json"
log "Done. Runtime: shell when python3 absent (or AKTO_HOOK_RUNTIME=shell)."
