// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/dashboard_service/v1/service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.dashboard_service.v1;

/**
 * Protobuf type {@code threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse}
 */
public final class FetchAlertFiltersResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse)
    FetchAlertFiltersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      FetchAlertFiltersResponse.class.getName());
  }
  // Use FetchAlertFiltersResponse.newBuilder() to construct.
  private FetchAlertFiltersResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FetchAlertFiltersResponse() {
    actors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    urls_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_FetchAlertFiltersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_FetchAlertFiltersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse.class, com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse.Builder.class);
  }

  public static final int ACTORS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList actors_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string actors = 1 [json_name = "actors"];</code>
   * @return A list containing the actors.
   */
  public com.google.protobuf.ProtocolStringList
      getActorsList() {
    return actors_;
  }
  /**
   * <code>repeated string actors = 1 [json_name = "actors"];</code>
   * @return The count of actors.
   */
  public int getActorsCount() {
    return actors_.size();
  }
  /**
   * <code>repeated string actors = 1 [json_name = "actors"];</code>
   * @param index The index of the element to return.
   * @return The actors at the given index.
   */
  public java.lang.String getActors(int index) {
    return actors_.get(index);
  }
  /**
   * <code>repeated string actors = 1 [json_name = "actors"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the actors at the given index.
   */
  public com.google.protobuf.ByteString
      getActorsBytes(int index) {
    return actors_.getByteString(index);
  }

  public static final int URLS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList urls_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string urls = 2 [json_name = "urls"];</code>
   * @return A list containing the urls.
   */
  public com.google.protobuf.ProtocolStringList
      getUrlsList() {
    return urls_;
  }
  /**
   * <code>repeated string urls = 2 [json_name = "urls"];</code>
   * @return The count of urls.
   */
  public int getUrlsCount() {
    return urls_.size();
  }
  /**
   * <code>repeated string urls = 2 [json_name = "urls"];</code>
   * @param index The index of the element to return.
   * @return The urls at the given index.
   */
  public java.lang.String getUrls(int index) {
    return urls_.get(index);
  }
  /**
   * <code>repeated string urls = 2 [json_name = "urls"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the urls at the given index.
   */
  public com.google.protobuf.ByteString
      getUrlsBytes(int index) {
    return urls_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < actors_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, actors_.getRaw(i));
    }
    for (int i = 0; i < urls_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, urls_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < actors_.size(); i++) {
        dataSize += computeStringSizeNoTag(actors_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getActorsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < urls_.size(); i++) {
        dataSize += computeStringSizeNoTag(urls_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUrlsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse)) {
      return super.equals(obj);
    }
    com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse other = (com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse) obj;

    if (!getActorsList()
        .equals(other.getActorsList())) return false;
    if (!getUrlsList()
        .equals(other.getUrlsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getActorsCount() > 0) {
      hash = (37 * hash) + ACTORS_FIELD_NUMBER;
      hash = (53 * hash) + getActorsList().hashCode();
    }
    if (getUrlsCount() > 0) {
      hash = (37 * hash) + URLS_FIELD_NUMBER;
      hash = (53 * hash) + getUrlsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse)
      com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_FetchAlertFiltersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_FetchAlertFiltersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse.class, com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse.Builder.class);
    }

    // Construct using com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      actors_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      urls_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_FetchAlertFiltersResponse_descriptor;
    }

    @java.lang.Override
    public com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse getDefaultInstanceForType() {
      return com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse build() {
      com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse buildPartial() {
      com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse result = new com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        actors_.makeImmutable();
        result.actors_ = actors_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        urls_.makeImmutable();
        result.urls_ = urls_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse) {
        return mergeFrom((com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse other) {
      if (other == com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse.getDefaultInstance()) return this;
      if (!other.actors_.isEmpty()) {
        if (actors_.isEmpty()) {
          actors_ = other.actors_;
          bitField0_ |= 0x00000001;
        } else {
          ensureActorsIsMutable();
          actors_.addAll(other.actors_);
        }
        onChanged();
      }
      if (!other.urls_.isEmpty()) {
        if (urls_.isEmpty()) {
          urls_ = other.urls_;
          bitField0_ |= 0x00000002;
        } else {
          ensureUrlsIsMutable();
          urls_.addAll(other.urls_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureActorsIsMutable();
              actors_.add(s);
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureUrlsIsMutable();
              urls_.add(s);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList actors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureActorsIsMutable() {
      if (!actors_.isModifiable()) {
        actors_ = new com.google.protobuf.LazyStringArrayList(actors_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string actors = 1 [json_name = "actors"];</code>
     * @return A list containing the actors.
     */
    public com.google.protobuf.ProtocolStringList
        getActorsList() {
      actors_.makeImmutable();
      return actors_;
    }
    /**
     * <code>repeated string actors = 1 [json_name = "actors"];</code>
     * @return The count of actors.
     */
    public int getActorsCount() {
      return actors_.size();
    }
    /**
     * <code>repeated string actors = 1 [json_name = "actors"];</code>
     * @param index The index of the element to return.
     * @return The actors at the given index.
     */
    public java.lang.String getActors(int index) {
      return actors_.get(index);
    }
    /**
     * <code>repeated string actors = 1 [json_name = "actors"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the actors at the given index.
     */
    public com.google.protobuf.ByteString
        getActorsBytes(int index) {
      return actors_.getByteString(index);
    }
    /**
     * <code>repeated string actors = 1 [json_name = "actors"];</code>
     * @param index The index to set the value at.
     * @param value The actors to set.
     * @return This builder for chaining.
     */
    public Builder setActors(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureActorsIsMutable();
      actors_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string actors = 1 [json_name = "actors"];</code>
     * @param value The actors to add.
     * @return This builder for chaining.
     */
    public Builder addActors(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureActorsIsMutable();
      actors_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string actors = 1 [json_name = "actors"];</code>
     * @param values The actors to add.
     * @return This builder for chaining.
     */
    public Builder addAllActors(
        java.lang.Iterable<java.lang.String> values) {
      ensureActorsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, actors_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string actors = 1 [json_name = "actors"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActors() {
      actors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string actors = 1 [json_name = "actors"];</code>
     * @param value The bytes of the actors to add.
     * @return This builder for chaining.
     */
    public Builder addActorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureActorsIsMutable();
      actors_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList urls_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureUrlsIsMutable() {
      if (!urls_.isModifiable()) {
        urls_ = new com.google.protobuf.LazyStringArrayList(urls_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string urls = 2 [json_name = "urls"];</code>
     * @return A list containing the urls.
     */
    public com.google.protobuf.ProtocolStringList
        getUrlsList() {
      urls_.makeImmutable();
      return urls_;
    }
    /**
     * <code>repeated string urls = 2 [json_name = "urls"];</code>
     * @return The count of urls.
     */
    public int getUrlsCount() {
      return urls_.size();
    }
    /**
     * <code>repeated string urls = 2 [json_name = "urls"];</code>
     * @param index The index of the element to return.
     * @return The urls at the given index.
     */
    public java.lang.String getUrls(int index) {
      return urls_.get(index);
    }
    /**
     * <code>repeated string urls = 2 [json_name = "urls"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the urls at the given index.
     */
    public com.google.protobuf.ByteString
        getUrlsBytes(int index) {
      return urls_.getByteString(index);
    }
    /**
     * <code>repeated string urls = 2 [json_name = "urls"];</code>
     * @param index The index to set the value at.
     * @param value The urls to set.
     * @return This builder for chaining.
     */
    public Builder setUrls(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUrlsIsMutable();
      urls_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string urls = 2 [json_name = "urls"];</code>
     * @param value The urls to add.
     * @return This builder for chaining.
     */
    public Builder addUrls(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUrlsIsMutable();
      urls_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string urls = 2 [json_name = "urls"];</code>
     * @param values The urls to add.
     * @return This builder for chaining.
     */
    public Builder addAllUrls(
        java.lang.Iterable<java.lang.String> values) {
      ensureUrlsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, urls_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string urls = 2 [json_name = "urls"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUrls() {
      urls_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string urls = 2 [json_name = "urls"];</code>
     * @param value The bytes of the urls to add.
     * @return This builder for chaining.
     */
    public Builder addUrlsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureUrlsIsMutable();
      urls_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse)
  }

  // @@protoc_insertion_point(class_scope:threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse)
  private static final com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse();
  }

  public static com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchAlertFiltersResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchAlertFiltersResponse>() {
    @java.lang.Override
    public FetchAlertFiltersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FetchAlertFiltersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchAlertFiltersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.akto.proto.threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

