// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/dashboard_service/v1/service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.dashboard_service.v1;

public interface FetchAlertFiltersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threat_protection.service.dashboard_service.v1.FetchAlertFiltersRequest)
    com.google.protobuf.MessageOrBuilder {
}
