// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/dashboard_service/v1/service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.dashboard_service.v1;

public interface FetchAlertFiltersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threat_protection.service.dashboard_service.v1.FetchAlertFiltersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string actors = 1 [json_name = "actors"];</code>
   * @return A list containing the actors.
   */
  java.util.List<java.lang.String>
      getActorsList();
  /**
   * <code>repeated string actors = 1 [json_name = "actors"];</code>
   * @return The count of actors.
   */
  int getActorsCount();
  /**
   * <code>repeated string actors = 1 [json_name = "actors"];</code>
   * @param index The index of the element to return.
   * @return The actors at the given index.
   */
  java.lang.String getActors(int index);
  /**
   * <code>repeated string actors = 1 [json_name = "actors"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the actors at the given index.
   */
  com.google.protobuf.ByteString
      getActorsBytes(int index);

  /**
   * <code>repeated string urls = 2 [json_name = "urls"];</code>
   * @return A list containing the urls.
   */
  java.util.List<java.lang.String>
      getUrlsList();
  /**
   * <code>repeated string urls = 2 [json_name = "urls"];</code>
   * @return The count of urls.
   */
  int getUrlsCount();
  /**
   * <code>repeated string urls = 2 [json_name = "urls"];</code>
   * @param index The index of the element to return.
   * @return The urls at the given index.
   */
  java.lang.String getUrls(int index);
  /**
   * <code>repeated string urls = 2 [json_name = "urls"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the urls at the given index.
   */
  com.google.protobuf.ByteString
      getUrlsBytes(int index);
}
