// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/dashboard_service/v1/service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.dashboard_service.v1;

/**
 * Protobuf type {@code threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse}
 */
public final class ListMaliciousRequestsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse)
    ListMaliciousRequestsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      ListMaliciousRequestsResponse.class.getName());
  }
  // Use ListMaliciousRequestsResponse.newBuilder() to construct.
  private ListMaliciousRequestsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListMaliciousRequestsResponse() {
    maliciousEvents_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_ListMaliciousRequestsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_ListMaliciousRequestsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse.class, com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse.Builder.class);
  }

  public static final int MALICIOUS_EVENTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage> maliciousEvents_;
  /**
   * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
   */
  @java.lang.Override
  public java.util.List<com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage> getMaliciousEventsList() {
    return maliciousEvents_;
  }
  /**
   * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessageOrBuilder> 
      getMaliciousEventsOrBuilderList() {
    return maliciousEvents_;
  }
  /**
   * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
   */
  @java.lang.Override
  public int getMaliciousEventsCount() {
    return maliciousEvents_.size();
  }
  /**
   * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
   */
  @java.lang.Override
  public com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage getMaliciousEvents(int index) {
    return maliciousEvents_.get(index);
  }
  /**
   * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
   */
  @java.lang.Override
  public com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessageOrBuilder getMaliciousEventsOrBuilder(
      int index) {
    return maliciousEvents_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private int total_ = 0;
  /**
   * <code>int32 total = 2 [json_name = "total"];</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }

  public static final int PAGE_FIELD_NUMBER = 3;
  private int page_ = 0;
  /**
   * <code>int32 page = 3 [json_name = "page"];</code>
   * @return The page.
   */
  @java.lang.Override
  public int getPage() {
    return page_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < maliciousEvents_.size(); i++) {
      output.writeMessage(1, maliciousEvents_.get(i));
    }
    if (total_ != 0) {
      output.writeInt32(2, total_);
    }
    if (page_ != 0) {
      output.writeInt32(3, page_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < maliciousEvents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, maliciousEvents_.get(i));
    }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, total_);
    }
    if (page_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, page_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse)) {
      return super.equals(obj);
    }
    com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse other = (com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse) obj;

    if (!getMaliciousEventsList()
        .equals(other.getMaliciousEventsList())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (getPage()
        != other.getPage()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMaliciousEventsCount() > 0) {
      hash = (37 * hash) + MALICIOUS_EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getMaliciousEventsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPage();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse)
      com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_ListMaliciousRequestsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_ListMaliciousRequestsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse.class, com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse.Builder.class);
    }

    // Construct using com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (maliciousEventsBuilder_ == null) {
        maliciousEvents_ = java.util.Collections.emptyList();
      } else {
        maliciousEvents_ = null;
        maliciousEventsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      total_ = 0;
      page_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.akto.proto.threat_protection.service.dashboard_service.v1.ServiceProto.internal_static_threat_protection_service_dashboard_service_v1_ListMaliciousRequestsResponse_descriptor;
    }

    @java.lang.Override
    public com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse getDefaultInstanceForType() {
      return com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse build() {
      com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse buildPartial() {
      com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse result = new com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse result) {
      if (maliciousEventsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          maliciousEvents_ = java.util.Collections.unmodifiableList(maliciousEvents_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.maliciousEvents_ = maliciousEvents_;
      } else {
        result.maliciousEvents_ = maliciousEventsBuilder_.build();
      }
    }

    private void buildPartial0(com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.total_ = total_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.page_ = page_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse) {
        return mergeFrom((com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse other) {
      if (other == com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse.getDefaultInstance()) return this;
      if (maliciousEventsBuilder_ == null) {
        if (!other.maliciousEvents_.isEmpty()) {
          if (maliciousEvents_.isEmpty()) {
            maliciousEvents_ = other.maliciousEvents_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMaliciousEventsIsMutable();
            maliciousEvents_.addAll(other.maliciousEvents_);
          }
          onChanged();
        }
      } else {
        if (!other.maliciousEvents_.isEmpty()) {
          if (maliciousEventsBuilder_.isEmpty()) {
            maliciousEventsBuilder_.dispose();
            maliciousEventsBuilder_ = null;
            maliciousEvents_ = other.maliciousEvents_;
            bitField0_ = (bitField0_ & ~0x00000001);
            maliciousEventsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMaliciousEventsFieldBuilder() : null;
          } else {
            maliciousEventsBuilder_.addAllMessages(other.maliciousEvents_);
          }
        }
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      if (other.getPage() != 0) {
        setPage(other.getPage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage m =
                  input.readMessage(
                      com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.parser(),
                      extensionRegistry);
              if (maliciousEventsBuilder_ == null) {
                ensureMaliciousEventsIsMutable();
                maliciousEvents_.add(m);
              } else {
                maliciousEventsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              total_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              page_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage> maliciousEvents_ =
      java.util.Collections.emptyList();
    private void ensureMaliciousEventsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        maliciousEvents_ = new java.util.ArrayList<com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage>(maliciousEvents_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessageOrBuilder> maliciousEventsBuilder_;

    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public java.util.List<com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage> getMaliciousEventsList() {
      if (maliciousEventsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(maliciousEvents_);
      } else {
        return maliciousEventsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public int getMaliciousEventsCount() {
      if (maliciousEventsBuilder_ == null) {
        return maliciousEvents_.size();
      } else {
        return maliciousEventsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage getMaliciousEvents(int index) {
      if (maliciousEventsBuilder_ == null) {
        return maliciousEvents_.get(index);
      } else {
        return maliciousEventsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public Builder setMaliciousEvents(
        int index, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage value) {
      if (maliciousEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMaliciousEventsIsMutable();
        maliciousEvents_.set(index, value);
        onChanged();
      } else {
        maliciousEventsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public Builder setMaliciousEvents(
        int index, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder builderForValue) {
      if (maliciousEventsBuilder_ == null) {
        ensureMaliciousEventsIsMutable();
        maliciousEvents_.set(index, builderForValue.build());
        onChanged();
      } else {
        maliciousEventsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public Builder addMaliciousEvents(com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage value) {
      if (maliciousEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMaliciousEventsIsMutable();
        maliciousEvents_.add(value);
        onChanged();
      } else {
        maliciousEventsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public Builder addMaliciousEvents(
        int index, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage value) {
      if (maliciousEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMaliciousEventsIsMutable();
        maliciousEvents_.add(index, value);
        onChanged();
      } else {
        maliciousEventsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public Builder addMaliciousEvents(
        com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder builderForValue) {
      if (maliciousEventsBuilder_ == null) {
        ensureMaliciousEventsIsMutable();
        maliciousEvents_.add(builderForValue.build());
        onChanged();
      } else {
        maliciousEventsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public Builder addMaliciousEvents(
        int index, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder builderForValue) {
      if (maliciousEventsBuilder_ == null) {
        ensureMaliciousEventsIsMutable();
        maliciousEvents_.add(index, builderForValue.build());
        onChanged();
      } else {
        maliciousEventsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public Builder addAllMaliciousEvents(
        java.lang.Iterable<? extends com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage> values) {
      if (maliciousEventsBuilder_ == null) {
        ensureMaliciousEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, maliciousEvents_);
        onChanged();
      } else {
        maliciousEventsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public Builder clearMaliciousEvents() {
      if (maliciousEventsBuilder_ == null) {
        maliciousEvents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        maliciousEventsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public Builder removeMaliciousEvents(int index) {
      if (maliciousEventsBuilder_ == null) {
        ensureMaliciousEventsIsMutable();
        maliciousEvents_.remove(index);
        onChanged();
      } else {
        maliciousEventsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder getMaliciousEventsBuilder(
        int index) {
      return getMaliciousEventsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessageOrBuilder getMaliciousEventsOrBuilder(
        int index) {
      if (maliciousEventsBuilder_ == null) {
        return maliciousEvents_.get(index);  } else {
        return maliciousEventsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public java.util.List<? extends com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessageOrBuilder> 
         getMaliciousEventsOrBuilderList() {
      if (maliciousEventsBuilder_ != null) {
        return maliciousEventsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(maliciousEvents_);
      }
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder addMaliciousEventsBuilder() {
      return getMaliciousEventsFieldBuilder().addBuilder(
          com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder addMaliciousEventsBuilder(
        int index) {
      return getMaliciousEventsFieldBuilder().addBuilder(
          index, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage malicious_events = 1 [json_name = "maliciousEvents"];</code>
     */
    public java.util.List<com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder> 
         getMaliciousEventsBuilderList() {
      return getMaliciousEventsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessageOrBuilder> 
        getMaliciousEventsFieldBuilder() {
      if (maliciousEventsBuilder_ == null) {
        maliciousEventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessage.Builder, com.akto.proto.threat_protection.message.malicious_event.dashboard.v1.DashboardMaliciousEventMessageOrBuilder>(
                maliciousEvents_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        maliciousEvents_ = null;
      }
      return maliciousEventsBuilder_;
    }

    private int total_ ;
    /**
     * <code>int32 total = 2 [json_name = "total"];</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return total_;
    }
    /**
     * <code>int32 total = 2 [json_name = "total"];</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {

      total_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total = 2 [json_name = "total"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000002);
      total_ = 0;
      onChanged();
      return this;
    }

    private int page_ ;
    /**
     * <code>int32 page = 3 [json_name = "page"];</code>
     * @return The page.
     */
    @java.lang.Override
    public int getPage() {
      return page_;
    }
    /**
     * <code>int32 page = 3 [json_name = "page"];</code>
     * @param value The page to set.
     * @return This builder for chaining.
     */
    public Builder setPage(int value) {

      page_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page = 3 [json_name = "page"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      page_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse)
  }

  // @@protoc_insertion_point(class_scope:threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse)
  private static final com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse();
  }

  public static com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListMaliciousRequestsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListMaliciousRequestsResponse>() {
    @java.lang.Override
    public ListMaliciousRequestsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListMaliciousRequestsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListMaliciousRequestsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.akto.proto.threat_protection.service.dashboard_service.v1.ListMaliciousRequestsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

