// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/dashboard_service/v1/service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.dashboard_service.v1;

public interface MaliciousRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threat_protection.service.dashboard_service.v1.MaliciousRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string actor = 2 [json_name = "actor"];</code>
   * @return The actor.
   */
  java.lang.String getActor();
  /**
   * <code>string actor = 2 [json_name = "actor"];</code>
   * @return The bytes for actor.
   */
  com.google.protobuf.ByteString
      getActorBytes();

  /**
   * <code>string filter_id = 3 [json_name = "filterId"];</code>
   * @return The filterId.
   */
  java.lang.String getFilterId();
  /**
   * <code>string filter_id = 3 [json_name = "filterId"];</code>
   * @return The bytes for filterId.
   */
  com.google.protobuf.ByteString
      getFilterIdBytes();

  /**
   * <code>string url = 4 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 4 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string method = 5 [json_name = "method"];</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 5 [json_name = "method"];</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string orig = 6 [json_name = "orig"];</code>
   * @return The orig.
   */
  java.lang.String getOrig();
  /**
   * <code>string orig = 6 [json_name = "orig"];</code>
   * @return The bytes for orig.
   */
  com.google.protobuf.ByteString
      getOrigBytes();

  /**
   * <code>string ip = 7 [json_name = "ip"];</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 7 [json_name = "ip"];</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string country = 8 [json_name = "country"];</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 8 [json_name = "country"];</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>int64 timestamp = 9 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
