// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/message/malicious_event/v1/message.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.message.malicious_event.v1;

public interface MaliciousEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threat_protection.message.malicious_event.v1.MaliciousEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string actor = 1 [json_name = "actor"];</code>
   * @return The actor.
   */
  java.lang.String getActor();
  /**
   * <code>string actor = 1 [json_name = "actor"];</code>
   * @return The bytes for actor.
   */
  com.google.protobuf.ByteString
      getActorBytes();

  /**
   * <code>string filter_id = 2 [json_name = "filterId"];</code>
   * @return The filterId.
   */
  java.lang.String getFilterId();
  /**
   * <code>string filter_id = 2 [json_name = "filterId"];</code>
   * @return The bytes for filterId.
   */
  com.google.protobuf.ByteString
      getFilterIdBytes();

  /**
<<<<<<< HEAD
   * <code>int64 detected_at = 3 [json_name = "detectedAt"];</code>
   * @return The detectedAt.
   */
  long getDetectedAt();

  /**
   * <code>string latest_api_ip = 4 [json_name = "latestApiIp"];</code>
   * @return The latestApiIp.
   */
  java.lang.String getLatestApiIp();
  /**
   * <code>string latest_api_ip = 4 [json_name = "latestApiIp"];</code>
   * @return The bytes for latestApiIp.
   */
  com.google.protobuf.ByteString
      getLatestApiIpBytes();

  /**
   * <code>string latest_api_endpoint = 5 [json_name = "latestApiEndpoint"];</code>
   * @return The latestApiEndpoint.
   */
  java.lang.String getLatestApiEndpoint();
  /**
   * <code>string latest_api_endpoint = 5 [json_name = "latestApiEndpoint"];</code>
   * @return The bytes for latestApiEndpoint.
   */
  com.google.protobuf.ByteString
      getLatestApiEndpointBytes();

  /**
   * <code>string latest_api_method = 6 [json_name = "latestApiMethod"];</code>
   * @return The latestApiMethod.
   */
  java.lang.String getLatestApiMethod();
  /**
   * <code>string latest_api_method = 6 [json_name = "latestApiMethod"];</code>
   * @return The bytes for latestApiMethod.
   */
  com.google.protobuf.ByteString
      getLatestApiMethodBytes();

  /**
   * <code>int32 latest_api_collection_id = 7 [json_name = "latestApiCollectionId"];</code>
   * @return The latestApiCollectionId.
   */
  int getLatestApiCollectionId();

  /**
   * <code>string latest_api_payload = 8 [json_name = "latestApiPayload"];</code>
   * @return The latestApiPayload.
   */
  java.lang.String getLatestApiPayload();
  /**
   * <code>string latest_api_payload = 8 [json_name = "latestApiPayload"];</code>
   * @return The bytes for latestApiPayload.
   */
  com.google.protobuf.ByteString
      getLatestApiPayloadBytes();

  /**
   * <code>.threat_protection.message.malicious_event.v1.MaliciousEvent.EventType event_type = 9 [json_name = "eventType"];</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.threat_protection.message.malicious_event.v1.MaliciousEvent.EventType event_type = 9 [json_name = "eventType"];</code>
   * @return The eventType.
   */
  com.akto.proto.threat_protection.message.malicious_event.v1.MaliciousEvent.EventType getEventType();
||||||| parent of 36e13656a (refactor code)
=======
   * <code>string ip = 3 [json_name = "ip"];</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 3 [json_name = "ip"];</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int64 timestamp = 4 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string url = 5 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 5 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string method = 6 [json_name = "method"];</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 6 [json_name = "method"];</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>int32 api_collection_id = 7 [json_name = "apiCollectionId"];</code>
   * @return The apiCollectionId.
   */
  int getApiCollectionId();

  /**
   * <code>string payload = 8 [json_name = "payload"];</code>
   * @return The payload.
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 8 [json_name = "payload"];</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();
>>>>>>> 36e13656a (refactor code)
}
