// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/message/malicious_event/v1/message.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.message.malicious_event.v1;

public final class MessageProto {
  private MessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      MessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_threat_protection_message_malicious_event_v1_MaliciousEventMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_threat_protection_message_malicious_event_v1_MaliciousEventMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:threat_protection/message/malicious_ev" +
      "ent/v1/message.proto\022,threat_protection." +
      "message.malicious_event.v1\032Hthreat_prote" +
      "ction/message/malicious_event/event_type" +
      "/v1/event_type.proto\"\265\003\n\025MaliciousEventM" +
      "essage\022\024\n\005actor\030\001 \001(\tR\005actor\022\033\n\tfilter_i" +
      "d\030\002 \001(\tR\010filterId\022\037\n\013detected_at\030\003 \001(\003R\n" +
      "detectedAt\022\"\n\rlatest_api_ip\030\004 \001(\tR\013lates" +
      "tApiIp\022.\n\023latest_api_endpoint\030\005 \001(\tR\021lat" +
      "estApiEndpoint\022*\n\021latest_api_method\030\006 \001(" +
      "\tR\017latestApiMethod\0227\n\030latest_api_collect" +
      "ion_id\030\007 \001(\005R\025latestApiCollectionId\022,\n\022l" +
      "atest_api_payload\030\010 \001(\tR\020latestApiPayloa" +
      "d\022a\n\nevent_type\030\t \001(\0162B.threat_protectio" +
      "n.message.malicious_event.event_type.v1." +
      "EventTypeR\teventTypeB\226\002\n;com.akto.proto." +
      "threat_protection.message.malicious_even" +
      "t.v1B\014MessageProtoP\001\242\002\003TMM\252\002*ThreatProte" +
      "ction.Message.MaliciousEvent.V1\312\002*Threat" +
      "Protection\\Message\\MaliciousEvent\\V1\342\0026T" +
      "hreatProtection\\Message\\MaliciousEvent\\V" +
      "1\\GPBMetadata\352\002-ThreatProtection::Messag" +
      "e::MaliciousEvent::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akto.proto.threat_protection.message.malicious_event.event_type.v1.EventTypeProto.getDescriptor(),
        });
    internal_static_threat_protection_message_malicious_event_v1_MaliciousEventMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_threat_protection_message_malicious_event_v1_MaliciousEventMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_threat_protection_message_malicious_event_v1_MaliciousEventMessage_descriptor,
        new java.lang.String[] { "Actor", "FilterId", "DetectedAt", "LatestApiIp", "LatestApiEndpoint", "LatestApiMethod", "LatestApiCollectionId", "LatestApiPayload", "EventType", });
    descriptor.resolveAllFeaturesImmutable();
    com.akto.proto.threat_protection.message.malicious_event.event_type.v1.EventTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
