// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/message/malicious_event/v1/message.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.message.malicious_event.v1;

public final class MessageProto {
  private MessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      MessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_threat_protection_message_malicious_event_v1_MaliciousEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_threat_protection_message_malicious_event_v1_MaliciousEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:threat_protection/message/malicious_ev" +
      "ent/v1/message.proto\022,threat_protection." +
      "message.malicious_event.v1\"\215\004\n\016Malicious" +
      "Event\022\024\n\005actor\030\001 \001(\tR\005actor\022\033\n\tfilter_id" +
      "\030\002 \001(\tR\010filterId\022\037\n\013detected_at\030\003 \001(\003R\nd" +
      "etectedAt\022\"\n\rlatest_api_ip\030\004 \001(\tR\013latest" +
      "ApiIp\022.\n\023latest_api_endpoint\030\005 \001(\tR\021late" +
      "stApiEndpoint\022*\n\021latest_api_method\030\006 \001(\t" +
      "R\017latestApiMethod\0227\n\030latest_api_collecti" +
      "on_id\030\007 \001(\005R\025latestApiCollectionId\022,\n\022la" +
      "test_api_payload\030\010 \001(\tR\020latestApiPayload" +
      "\022e\n\nevent_type\030\t \001(\0162F.threat_protection" +
      ".message.malicious_event.v1.MaliciousEve" +
      "nt.EventTypeR\teventType\"Y\n\tEventType\022\032\n\026" +
      "EVENT_TYPE_UNSPECIFIED\020\000\022\025\n\021EVENT_TYPE_S" +
      "INGLE\020\001\022\031\n\025EVENT_TYPE_AGGREGATED\020\002B\226\002\n;c" +
      "om.akto.proto.threat_protection.message." +
      "malicious_event.v1B\014MessageProtoP\001\242\002\003TMM" +
      "\252\002*ThreatProtection.Message.MaliciousEve" +
      "nt.V1\312\002*ThreatProtection\\Message\\Malicio" +
      "usEvent\\V1\342\0026ThreatProtection\\Message\\Ma" +
      "liciousEvent\\V1\\GPBMetadata\352\002-ThreatProt" +
      "ection::Message::MaliciousEvent::V1b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_threat_protection_message_malicious_event_v1_MaliciousEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_threat_protection_message_malicious_event_v1_MaliciousEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_threat_protection_message_malicious_event_v1_MaliciousEvent_descriptor,
        new java.lang.String[] { "Actor", "FilterId", "DetectedAt", "LatestApiIp", "LatestApiEndpoint", "LatestApiMethod", "LatestApiCollectionId", "LatestApiPayload", "EventType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
