#!/bin/bash

# ========================================================================================
# MCP Endpoint Shield - OpenClaw (Clawdbot) Config Updater
# ========================================================================================
# Updates openclaw.json:
#   1. Adds models.providers.secure-local block
#   2. Updates agents.defaults.model.primary and agents.defaults.models
#   3. Generates/reads .env file at ~/.openclaw/akto.env
# ========================================================================================

set -e

# ── Defaults (no $HOME — safe for live response) ──────────────────────────────
TARGET_USER_HOME="${TARGET_USER_HOME:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
AKTO_GUARDRAILS_URL="${AKTO_GUARDRAILS_URL:-}"
ORIGINAL_PROVIDER="${ORIGINAL_PROVIDER:-}"
MODEL_API="${MODEL_API:-}"
MODEL_ID="${MODEL_ID:-}"

# ── Parse KEY=VALUE args ──────────────────────────────────────────────────────
for a in "$@"; do
    case "$a" in
        TARGET_USER_HOME=*)  TARGET_USER_HOME="${a#TARGET_USER_HOME=}" ;;
        OPENAI_API_KEY=*)    OPENAI_API_KEY="${a#OPENAI_API_KEY=}" ;;
        AKTO_GUARDRAILS_URL=*) AKTO_GUARDRAILS_URL="${a#AKTO_GUARDRAILS_URL=}" ;;
        ORIGINAL_PROVIDER=*) ORIGINAL_PROVIDER="${a#ORIGINAL_PROVIDER=}" ;;
        MODEL_API=*)         MODEL_API="${a#MODEL_API=}" ;;
        MODEL_ID=*)          MODEL_ID="${a#MODEL_ID=}" ;;
    esac
done

[ -n "$OPENAI_API_KEY" ]    && export OPENAI_API_KEY
[ -n "$AKTO_PROXY_URL" ]    && export AKTO_PROXY_URL
[ -n "$ORIGINAL_PROVIDER" ] && export ORIGINAL_PROVIDER
[ -n "$MODEL_API" ]         && export MODEL_API
[ -n "$MODEL_ID" ]          && export MODEL_ID

log() {
    echo "[OpenClaw Config] $1"
}

log_error() {
    echo "[OpenClaw Config] ERROR: $1" >&2
}

# ── Load .env if it exists, then apply arg overrides on top ──────────────────
load_env() {
    local env_file="$1"

    if [ -f "$env_file" ]; then
        log "Loading env from: $env_file"
        # Source only KEY=VALUE lines, skip comments and blanks
        while IFS= read -r line; do
            [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
            key="${line%%=*}"
            val="${line#*=}"
            # Only set if not already overridden by CLI arg
            case "$key" in
                AKTO_PROXY_URL)    [ -z "$AKTO_PROXY_URL" ]    && AKTO_PROXY_URL="$val" ;;
                OPENAI_API_KEY)    [ -z "$OPENAI_API_KEY" ]    && OPENAI_API_KEY="$val" ;;
                ORIGINAL_PROVIDER) [ -z "$ORIGINAL_PROVIDER" ] && ORIGINAL_PROVIDER="$val" ;;
                MODEL_API)         [ -z "$MODEL_API" ]         && MODEL_API="$val" ;;
                MODEL_ID)          [ -z "$MODEL_ID" ]          && MODEL_ID="$val" ;;
            esac
        done < "$env_file"
        log "✓ Env file loaded"
    else
        log "No existing env file found — will create one at: $env_file"
    fi

    # Apply fallbacks after .env + CLI args are resolved
    AKTO_PROXY_URL="${AKTO_PROXY_URL:-http://localhost:8080}"
    ORIGINAL_PROVIDER="${ORIGINAL_PROVIDER:-openai/gpt-4o-mini}"
}

# ── Write .env file ───────────────────────────────────────────────────────────
write_env() {
    local env_file="$1"

    cat > "$env_file" <<EOF
# Akto MCP Endpoint Shield - OpenClaw config
# Auto-generated by install_openclaw_guardrails_sentinelone.sh — $(date)

AKTO_PROXY_URL=${AKTO_PROXY_URL}
OPENAI_API_KEY=${OPENAI_API_KEY}
ORIGINAL_PROVIDER=${ORIGINAL_PROVIDER}
MODEL_API=${MODEL_API}
MODEL_ID=${MODEL_ID}
EOF

    chmod 600 "$env_file"
    log "✓ Env file written: $env_file"
}

# ── Preflight checks ──────────────────────────────────────────────────────────
check_requirements() {
    if ! command -v jq >/dev/null 2>&1; then
        log_error "jq is required but not installed. Run: brew install jq"
        exit 1
    fi

    if [ ! -f "$CONFIG_FILE" ]; then
        log "Skipping $TARGET_USER_HOME — openclaw.json not found at: $CONFIG_FILE"
        return 1
    fi

    if ! jq empty "$CONFIG_FILE" 2>/dev/null; then
        log_error "openclaw.json is not valid JSON. Aborting."
        exit 1
    fi
}

# ── Backup ────────────────────────────────────────────────────────────────────
backup_config() {
    local backup="$CONFIG_FILE.backup.$(date +%s)"
    cp "$CONFIG_FILE" "$backup"
    log "✓ Backup saved: $backup"
}

# ── Build and merge both blocks ───────────────────────────────────────────────
update_config() {
    local base_url="${AKTO_GUARDRAILS_URL%/}"

    local api_key_value
    if [ -n "$OPENAI_API_KEY" ]; then
        api_key_value="${OPENAI_API_KEY}; X-Original-Provider: ${ORIGINAL_PROVIDER}"
    else
        api_key_value="\${OPENAI_API_KEY}; X-Original-Provider: ${ORIGINAL_PROVIDER}"
    fi

    local provider_key="secure-local/${MODEL_ID}"

    local patch
    patch=$(jq -n \
        --arg apiKey      "$api_key_value" \
        --arg baseUrl     "$base_url" \
        --arg modelApi    "$MODEL_API" \
        --arg modelId     "$MODEL_ID" \
        --arg providerKey "$provider_key" \
        '{
            models: {
                providers: {
                    "secure-local": {
                        api:     $modelApi,
                        apiKey:  $apiKey,
                        baseUrl: $baseUrl,
                        models: [
                            { id: $modelId, name: $modelId }
                        ]
                    }
                }
            },
            agents: {
                defaults: {
                    model: {
                        primary: $providerKey
                    },
                    models: {
                        ($providerKey): {}
                    }
                }
            }
        }')

    local updated
    updated=$(jq --argjson patch "$patch" '. * $patch' "$CONFIG_FILE")

    if ! echo "$updated" | jq empty 2>/dev/null; then
        log_error "Merged JSON is invalid. Aborting — original file untouched."
        exit 1
    fi

    echo "$updated" > "$CONFIG_FILE"
}

# ── Per-user install ──────────────────────────────────────────────────────────
install_for_user() {
    local user_home="$1"
    TARGET_USER_HOME="$user_home"
    CONFIG_FILE="$user_home/.openclaw/openclaw.json"
    ENV_FILE="$user_home/.openclaw/akto.env"

    log ""
    log "=== Processing user home: $user_home ==="
    log "Config file : $CONFIG_FILE"

    check_requirements || return 0

    # Load .env first, CLI args take priority
    load_env "$ENV_FILE"

    log "Proxy URL         : $AKTO_PROXY_URL"
    log "Original Provider : $ORIGINAL_PROVIDER"
    log "Model API         : $MODEL_API"
    log "Model ID          : $MODEL_ID"

    # Write/update .env with resolved values
    write_env "$ENV_FILE"

    backup_config
    update_config

    log ""
    log "=========================================="
    log "✅ openclaw.json updated successfully!"
    log "=========================================="
    log "• models.providers.secure-local — added"
    log "• agents.defaults.model.primary — set to secure-local/${MODEL_ID}"
    log "• agents.defaults.models        — set to secure-local/${MODEL_ID}"
    log "• env file                      — $ENV_FILE"
}

# ── Main execution ────────────────────────────────────────────────────────────
if [ -n "$TARGET_USER_HOME" ]; then
    # Single user mode
    if [ ! -d "$TARGET_USER_HOME" ]; then
        log_error "TARGET_USER_HOME is not a valid directory: $TARGET_USER_HOME"
        exit 1
    fi
    install_for_user "$TARGET_USER_HOME"
else
    # Multi-user mode: iterate all valid users
    EXIT_CODE=0
    for u in /Users/*/ /home/*/; do
        u="${u%/}"
        base="$(basename "$u")"
        [ "$base" = "Shared" ] && continue
        [ "$base" = "Guest" ]  && continue
        [[ "$base" == .* ]]    && continue
        [ -d "$u" ]            || continue
        install_for_user "$u" || EXIT_CODE=1
    done
    exit $EXIT_CODE
fi
