# ========================================================================================
# MCP Endpoint Shield - OpenClaw (Clawdbot) Config Updater (PowerShell)
# ========================================================================================
# Updates openclaw.json:
#   1. Adds models.providers.secure-local block
#   2. Updates agents.defaults.model.primary and agents.defaults.models
#   3. Generates/reads .env file at %USERPROFILE%\.openclaw\akto.env
# ========================================================================================

param(
    [string]$TargetUserHome = "",
    [string]$OpenAIApiKey = "",
    [string]$AktoProxyUrl = "",
    [string]$OriginalProvider = "",
    [string]$ModelApi = "",
    [string]$ModelId = ""
)

# ── Parse KEY=VALUE args from remaining parameters ───────────────────────────
foreach ($arg in $args) {
    if ($arg -match '^([^=]+)=(.*)$') {
        $key = $matches[1]
        $val = $matches[2]
        switch ($key) {
            "TARGET_USER_HOME"  { $TargetUserHome = $val }
            "OPENAI_API_KEY"    { $OpenAIApiKey = $val }
            "AKTO_PROXY_URL"    { $AktoProxyUrl = $val }
            "ORIGINAL_PROVIDER" { $OriginalProvider = $val }
            "MODEL_API"         { $ModelApi = $val }
            "MODEL_ID"          { $ModelId = $val }
        }
    }
}

function Write-Log {
    param([string]$Message)
    Write-Host "[OpenClaw Config] $Message"
}

function Write-LogError {
    param([string]$Message)
    Write-Host "[OpenClaw Config] ERROR: $Message" -ForegroundColor Red
}

# ── Load .env if it exists, then apply arg overrides on top ──────────────────
function Load-Env {
    param([string]$EnvFile)

    if (Test-Path $EnvFile) {
        Write-Log "Loading env from: $EnvFile"
        Get-Content $EnvFile | ForEach-Object {
            $line = $_.Trim()
            if ($line -and !$line.StartsWith('#')) {
                if ($line -match '^([^=]+)=(.*)$') {
                    $key = $matches[1]
                    $val = $matches[2]
                    
                    switch ($key) {
                        "AKTO_PROXY_URL"    { if (!$script:AktoProxyUrl) { $script:AktoProxyUrl = $val } }
                        "OPENAI_API_KEY"    { if (!$script:OpenAIApiKey) { $script:OpenAIApiKey = $val } }
                        "ORIGINAL_PROVIDER" { if (!$script:OriginalProvider) { $script:OriginalProvider = $val } }
                        "MODEL_API"         { if (!$script:ModelApi) { $script:ModelApi = $val } }
                        "MODEL_ID"          { if (!$script:ModelId) { $script:ModelId = $val } }
                    }
                }
            }
        }
        Write-Log "✓ Env file loaded"
    } else {
        Write-Log "No existing env file found — will create one at: $EnvFile"
    }

    # Apply fallbacks
    if (!$script:AktoProxyUrl) { $script:AktoProxyUrl = "http://localhost:8080" }
    if (!$script:OriginalProvider) { $script:OriginalProvider = "openai/gpt-4o-mini" }
}

# ── Write .env file ───────────────────────────────────────────────────────────
function Write-Env {
    param([string]$EnvFile)

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $content = @"
# Akto MCP Endpoint Shield - OpenClaw config
# Auto-generated by install_openclaw_guardrails_sentinelone.ps1 — $timestamp

AKTO_PROXY_URL=$AktoProxyUrl
OPENAI_API_KEY=$OpenAIApiKey
ORIGINAL_PROVIDER=$OriginalProvider
MODEL_API=$ModelApi
MODEL_ID=$ModelId
"@

    $content | Out-File -FilePath $EnvFile -Encoding UTF8
    Write-Log "✓ Env file written: $EnvFile"
}

# ── Preflight checks ──────────────────────────────────────────────────────────
function Test-Requirements {
    param([string]$ConfigFile)

    if (!(Test-Path $ConfigFile)) {
        Write-Log "Skipping $TargetUserHome — openclaw.json not found at: $ConfigFile"
        return $false
    }

    try {
        $null = Get-Content $ConfigFile -Raw | ConvertFrom-Json
    } catch {
        Write-LogError "openclaw.json is not valid JSON. Aborting."
        exit 1
    }

    return $true
}

# ── Backup ────────────────────────────────────────────────────────────────────
function Backup-Config {
    param([string]$ConfigFile)

    $timestamp = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    $backup = "$ConfigFile.backup.$timestamp"
    Copy-Item $ConfigFile $backup
    Write-Log "✓ Backup saved: $backup"
}

# ── Build and merge both blocks ───────────────────────────────────────────────
function Update-Config {
    param([string]$ConfigFile)

    $baseUrl = $AktoProxyUrl.TrimEnd('/')

    $apiKeyValue = if ($OpenAIApiKey) {
        "$OpenAIApiKey; X-Original-Provider: $OriginalProvider"
    } else {
        "`${OPENAI_API_KEY}; X-Original-Provider: $OriginalProvider"
    }

    $providerKey = "secure-local/$ModelId"

    # Load existing config
    $config = Get-Content $ConfigFile -Raw | ConvertFrom-Json

    # Create secure-local provider
    if (!$config.models) { $config | Add-Member -NotePropertyName models -NotePropertyValue @{} }
    if (!$config.models.providers) { $config.models | Add-Member -NotePropertyName providers -NotePropertyValue @{} }
    
    $secureLocal = @{
        api = $ModelApi
        apiKey = $apiKeyValue
        baseUrl = $baseUrl
        models = @(
            @{
                id = $ModelId
                name = $ModelId
            }
        )
    }
    
    $config.models.providers | Add-Member -NotePropertyName "secure-local" -NotePropertyValue $secureLocal -Force

    # Update agents defaults
    if (!$config.agents) { $config | Add-Member -NotePropertyName agents -NotePropertyValue @{} }
    if (!$config.agents.defaults) { $config.agents | Add-Member -NotePropertyName defaults -NotePropertyValue @{} }
    if (!$config.agents.defaults.model) { $config.agents.defaults | Add-Member -NotePropertyName model -NotePropertyValue @{} }
    
    $config.agents.defaults.model | Add-Member -NotePropertyName primary -NotePropertyValue $providerKey -Force
    
    if (!$config.agents.defaults.models) { 
        $config.agents.defaults | Add-Member -NotePropertyName models -NotePropertyValue @{} 
    }
    $config.agents.defaults.models | Add-Member -NotePropertyName $providerKey -NotePropertyValue @{} -Force

    # Write back
    $config | ConvertTo-Json -Depth 10 | Set-Content $ConfigFile -Encoding UTF8
}

# ── Per-user install ──────────────────────────────────────────────────────────
function Install-ForUser {
    param([string]$UserHome)

    $script:TargetUserHome = $UserHome
    $ConfigFile = Join-Path $UserHome ".openclaw\openclaw.json"
    $EnvFile = Join-Path $UserHome ".openclaw\akto.env"

    Write-Log ""
    Write-Log "=== Processing user home: $UserHome ==="
    Write-Log "Config file : $ConfigFile"

    if (!(Test-Requirements -ConfigFile $ConfigFile)) {
        return
    }

    # Load .env first, CLI args take priority
    Load-Env -EnvFile $EnvFile

    Write-Log "Proxy URL         : $AktoProxyUrl"
    Write-Log "Original Provider : $OriginalProvider"
    Write-Log "Model API         : $ModelApi"
    Write-Log "Model ID          : $ModelId"

    # Write/update .env with resolved values
    Write-Env -EnvFile $EnvFile

    Backup-Config -ConfigFile $ConfigFile
    Update-Config -ConfigFile $ConfigFile

    Write-Log ""
    Write-Log "=========================================="
    Write-Log "✅ openclaw.json updated successfully!"
    Write-Log "=========================================="
    Write-Log "• models.providers.secure-local — added"
    Write-Log "• agents.defaults.model.primary — set to secure-local/$ModelId"
    Write-Log "• agents.defaults.models        — set to secure-local/$ModelId"
    Write-Log "• env file                      — $EnvFile"
}

# ── Main execution ────────────────────────────────────────────────────────────
if ($TargetUserHome) {
    # Single user mode
    if (!(Test-Path $TargetUserHome)) {
        Write-LogError "TARGET_USER_HOME is not a valid directory: $TargetUserHome"
        exit 1
    }
    Install-ForUser -UserHome $TargetUserHome
} else {
    # Multi-user mode: iterate all valid users
    $users = Get-ChildItem "C:\Users" -Directory | Where-Object {
        $_.Name -notin @("Public", "Default", "Default User", "All Users") -and
        !$_.Name.StartsWith('.')
    }

    foreach ($user in $users) {
        try {
            Install-ForUser -UserHome $user.FullName
        } catch {
            Write-LogError "Failed to process user: $($user.FullName)"
            Write-LogError $_.Exception.Message
        }
    }
}
