#!/usr/bin/env python3
"""Download the cl100k_base BPE vocab and emit src/vocab_blob.py (gzip+base64).

tiktoken can't fetch the vocab at runtime in the Worker (no blocking network),
so we embed it as a Python module. Run once; commit the generated file.
Regenerate with:  python scripts/gen_vocab.py
"""

import base64
import gzip
import pathlib
import urllib.request

URL = "https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken"


def main() -> None:
    raw = urllib.request.urlopen(URL, timeout=60).read()
    gz = gzip.compress(raw, 9)
    b64 = base64.b64encode(gz).decode()
    out = pathlib.Path(__file__).resolve().parent.parent / "src" / "vocab_blob.py"
    out.write_text(
        "# Auto-generated by scripts/gen_vocab.py — cl100k_base vocab (gzip+base64).\n"
        "# Regenerate with: python scripts/gen_vocab.py\n"
        "import base64\n"
        "import gzip\n\n"
        f'_B64 = "{b64}"\n\n\n'
        "def raw_bytes() -> bytes:\n"
        "    return gzip.decompress(base64.b64decode(_B64))\n"
    )
    print(f"wrote {out}  (raw={len(raw)} gz={len(gz)} module={out.stat().st_size})")


if __name__ == "__main__":
    main()
