#!/usr/bin/env bash
# install-shell-hooks.sh - Install Akto MCP Endpoint Shield hooks for VS Code Copilot
#
# Installs to ~/.vscode/copilot/hooks/akto/ and writes hooks.json.
# Generates runtime-detecting wrappers (python3 → pwsh → bash).
# Wraps include the ENABLE_MCP_HOOKS_VSCODE live-flag guard.
#
# Usage:
#   install-shell-hooks.sh [options]
#
# Options:
#   --ingestion-url URL   Akto gateway URL (required for real use)
#   --api-token TOKEN     API token for auth
#   --device-id ID        Override device identifier
#   --home DIR            Override HOME for install path (default: $HOME)
#   --src DIR             Override source bash/ps directory (default: sibling dir)
#   --help
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Source bash hooks are shared with github-cli-hooks
GITHUB_SH="$SCRIPT_DIR/../github-cli-hooks"

INGESTION_URL="${AKTO_DATA_INGESTION_URL:-}"
API_TOKEN="${AKTO_API_TOKEN:-}"
DEVICE_ID_OVERRIDE="${DEVICE_ID:-}"
TARGET_HOME="$HOME"
SRC_BASH="${GITHUB_SH}/bash"
SRC_PS="${GITHUB_SH}/powershell"

info()  { printf '\033[0;32m[INFO]\033[0m  %s\n' "$*"; }
warn()  { printf '\033[0;33m[WARN]\033[0m  %s\n' "$*"; }
error() { printf '\033[0;31m[ERROR]\033[0m %s\n' "$*" >&2; }

while [[ $# -gt 0 ]]; do
  case $1 in
    --ingestion-url) INGESTION_URL="$2"; shift 2 ;;
    --api-token)     API_TOKEN="$2"; shift 2 ;;
    --device-id)     DEVICE_ID_OVERRIDE="$2"; shift 2 ;;
    --home)          TARGET_HOME="$2"; shift 2 ;;
    --src)           SRC_BASH="$2/bash"; SRC_PS="$2/powershell"; shift 2 ;;
    --help|-h)
      echo "Usage: $0 [--ingestion-url URL] [--api-token TOKEN] [--device-id ID]"
      exit 0 ;;
    *) error "Unknown argument: $1"; exit 1 ;;
  esac
done

HOOKS_DIR="$TARGET_HOME/.vscode/copilot/hooks/akto"
HOOKS_JSON="$TARGET_HOME/.vscode/copilot/hooks/hooks.json"
LOG_DIR="$TARGET_HOME/.vscode/copilot/hooks/akto/logs"
AKTO_CONFIG_FILE="$TARGET_HOME/.akto-mcp-endpoint-shield/config/config.env"

info "Installing Akto hooks for VS Code Copilot → $HOOKS_DIR"
mkdir -p "$HOOKS_DIR/bash" "$HOOKS_DIR/powershell" "$LOG_DIR"

# ── auto-detect device id if not provided ─────────────────────────────────────
DEVICE_ID="${DEVICE_ID_OVERRIDE:-}"
if [ -z "$DEVICE_ID" ]; then
  _name="$(scutil --get ComputerName 2>/dev/null | tr ' ' '-')" || true
  [ -z "$_name" ] && _name="$(hostname 2>/dev/null | sed 's/\.local$//' | tr ' ' '-')"
  _mid=""
  if command -v ioreg >/dev/null 2>&1; then
    _mid="$(ioreg -rd1 -c IOPlatformExpertDevice 2>/dev/null | grep IOPlatformUUID | awk -F'"' '{print $4}' | tr -d '-' | tr '[:upper:]' '[:lower:]')" || true
  fi
  [ -z "$_mid" ] && [ -r /etc/machine-id ] && _mid="$(tr -d '-' < /etc/machine-id | head -c8)"
  DEVICE_ID="${_name}-${_mid:0:8}"
fi

# ── copy bash hooks ────────────────────────────────────────────────────────────
if [ -d "$SRC_BASH" ]; then
  for f in akto_common.sh akto-validate-prompt.sh akto-validate-pre-tool.sh akto-validate-post-tool.sh akto-hooks.sh; do
    if [ -f "$SRC_BASH/$f" ]; then
      cp "$SRC_BASH/$f" "$HOOKS_DIR/bash/$f"
      chmod +x "$HOOKS_DIR/bash/$f"
      info "  Copied bash/$f"
    else
      warn "  Missing: bash/$f (skipped)"
    fi
  done
else
  warn "Source bash dir not found: $SRC_BASH"
fi

# ── copy PowerShell hooks ──────────────────────────────────────────────────────
if [ -d "$SRC_PS" ]; then
  for f in AktoCommon.psm1 akto-validate-prompt.ps1 akto-validate-pre-tool.ps1 akto-validate-post-tool.ps1 akto-hooks.ps1; do
    if [ -f "$SRC_PS/$f" ]; then
      cp "$SRC_PS/$f" "$HOOKS_DIR/powershell/$f"
      info "  Copied powershell/$f"
    else
      warn "  Missing: powershell/$f (skipped)"
    fi
  done
else
  warn "Source PowerShell dir not found: $SRC_PS"
fi

# ── write runtime-detecting wrapper scripts ────────────────────────────────────
write_wrapper() {
  local hook_name="$1"    # prompt | pre-tool | post-tool
  local bash_script="$2"  # akto-validate-<X>.sh
  local ps_script="$3"    # akto-validate-<X>.ps1
  local python_script="$4"  # akto-validate-<X>.py

  local wrapper="$HOOKS_DIR/akto-validate-${hook_name}-wrapper.sh"
  cat > "$wrapper" << WRAPPER
#!/bin/bash
# Akto VS Code Copilot hook wrapper (runtime-detecting).
# Generated by install-shell-hooks.sh

# Live-flag guard
_akto_cfg="$AKTO_CONFIG_FILE"
[ -f "\$_akto_cfg" ] && source "\$_akto_cfg"
[ "\${ENABLE_MCP_HOOKS_VSCODE:-}" = "false" ] && exit 0

# Environment
export MODE="atlas"
export AKTO_DATA_INGESTION_URL="$INGESTION_URL"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="vscode"
export CONTEXT_SOURCE="ENDPOINT"
export AKTO_API_TOKEN="$API_TOKEN"
export DEVICE_ID="$DEVICE_ID"
export LOG_DIR="$LOG_DIR"

_AKTO_DIR="$HOOKS_DIR"
_RUNTIME="\${AKTO_HOOK_RUNTIME:-}"

if [ -z "\$_RUNTIME" ]; then
  if command -v python3 >/dev/null 2>&1; then _RUNTIME="python3"
  elif command -v pwsh >/dev/null 2>&1; then _RUNTIME="pwsh"
  else _RUNTIME="bash"; fi
fi

case "\$_RUNTIME" in
  python3)
    _PY="\${AKTO_PYTHON_HOOKS_DIR:-\$_AKTO_DIR}/$python_script"
    if [ -f "\$_PY" ]; then exec python3 "\$_PY" "\$@"; fi
    exec bash "\$_AKTO_DIR/bash/$bash_script" "\$@" ;;
  pwsh|powershell)
    exec pwsh -NonInteractive -NoProfile -File "\$_AKTO_DIR/powershell/$ps_script" "\$@" ;;
  bash|*)
    exec bash "\$_AKTO_DIR/bash/$bash_script" "\$@" ;;
esac
WRAPPER
  chmod +x "$wrapper"
  info "  Wrote wrapper: akto-validate-${hook_name}-wrapper.sh"
}

info "Writing runtime-detecting wrappers..."
write_wrapper "prompt"    "akto-validate-prompt.sh"    "akto-validate-prompt.ps1"    "akto-validate-prompt.py"
write_wrapper "pre-tool"  "akto-validate-pre-tool.sh"  "akto-validate-pre-tool.ps1"  "akto-validate-pre-tool.py"
write_wrapper "post-tool" "akto-validate-post-tool.sh" "akto-validate-post-tool.ps1" "akto-validate-post-tool.py"

# ── write hooks.json ───────────────────────────────────────────────────────────
mkdir -p "$(dirname "$HOOKS_JSON")"
cat > "$HOOKS_JSON" << JSON
{
  "version": 1,
  "hooks": {
    "userPromptSubmitted": [
      {
        "type": "command",
        "bash": "$HOOKS_DIR/akto-validate-prompt-wrapper.sh",
        "comment": "Validate prompts against Akto Guardrails",
        "timeoutSec": 30
      }
    ],
    "preToolUse": [
      {
        "type": "command",
        "bash": "$HOOKS_DIR/akto-validate-pre-tool-wrapper.sh",
        "comment": "Validate and block tool execution based on Akto Guardrails policies",
        "timeoutSec": 30
      }
    ],
    "postToolUse": [
      {
        "type": "command",
        "bash": "$HOOKS_DIR/akto-validate-post-tool-wrapper.sh",
        "comment": "Validate tool results against Akto Guardrails and ingest for monitoring",
        "timeoutSec": 30
      }
    ]
  }
}
JSON
info "Wrote hooks.json → $HOOKS_JSON"

# ── summary ────────────────────────────────────────────────────────────────────
info ""
info "Installation complete!"
info ""
info "Hooks installed to:  $HOOKS_DIR"
info "Hooks config:        $HOOKS_JSON"
info ""
info "Required environment variables (set in wrapper or environment):"
info "  AKTO_DATA_INGESTION_URL   Akto gateway URL"
info ""
info "VS Code Copilot should automatically load hooks from:"
info "  ~/.vscode/copilot/hooks/hooks.json"
info ""
if [ -z "$INGESTION_URL" ]; then
  warn "AKTO_DATA_INGESTION_URL is not set — update the wrapper scripts before using."
fi
