// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/malicious_alert_service/v1/consumer_service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.malicious_alert_service.v1;

public final class ConsumerServiceProto {
  private ConsumerServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      ConsumerServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_threat_protection_service_malicious_alert_service_v1_SampleMaliciousEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_threat_protection_service_malicious_alert_service_v1_SampleMaliciousEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nKthreat_protection/service/malicious_al" +
      "ert_service/v1/consumer_service.proto\0224t" +
      "hreat_protection.service.malicious_alert" +
      "_service.v1\"\025\n\023RecordAlertResponse\"\264\001\n\024S" +
      "ampleMaliciousEvent\022\016\n\002ip\030\001 \001(\tR\002ip\022\034\n\tt" +
      "imestamp\030\002 \001(\003R\ttimestamp\022\020\n\003url\030\003 \001(\tR\003" +
      "url\022\026\n\006method\030\004 \001(\tR\006method\022*\n\021api_colle" +
      "ction_id\030\005 \001(\005R\017apiCollectionId\022\030\n\007paylo" +
      "ad\030\006 \001(\tR\007payload\"\370\001\n\022RecordAlertRequest" +
      "\022\024\n\005actor\030\001 \001(\tR\005actor\022\033\n\tfilter_id\030\002 \001(" +
      "\tR\010filterId\022!\n\014total_events\030\003 \001(\005R\013total" +
      "Events\022\037\n\013detected_at\030\004 \001(\003R\ndetectedAt\022" +
      "k\n\013sample_data\030\005 \003(\0132J.threat_protection" +
      ".service.malicious_alert_service.v1.Samp" +
      "leMaliciousEventR\nsampleData2\276\001\n\025Malicio" +
      "usAlertService\022\244\001\n\013RecordAlert\022H.threat_" +
      "protection.service.malicious_alert_servi" +
      "ce.v1.RecordAlertRequest\032I.threat_protec" +
      "tion.service.malicious_alert_service.v1." +
      "RecordAlertResponse\"\000B\302\002\nCcom.akto.proto" +
      ".threat_protection.service.malicious_ale" +
      "rt_service.v1B\024ConsumerServiceProtoP\001\242\002\003" +
      "TSM\252\0021ThreatProtection.Service.Malicious" +
      "AlertService.V1\312\0021ThreatProtection\\Servi" +
      "ce\\MaliciousAlertService\\V1\342\002=ThreatProt" +
      "ection\\Service\\MaliciousAlertService\\V1\\" +
      "GPBMetadata\352\0024ThreatProtection::Service:" +
      ":MaliciousAlertService::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertResponse_descriptor,
        new java.lang.String[] { });
    internal_static_threat_protection_service_malicious_alert_service_v1_SampleMaliciousEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_threat_protection_service_malicious_alert_service_v1_SampleMaliciousEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_threat_protection_service_malicious_alert_service_v1_SampleMaliciousEvent_descriptor,
        new java.lang.String[] { "Ip", "Timestamp", "Url", "Method", "ApiCollectionId", "Payload", });
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_threat_protection_service_malicious_alert_service_v1_RecordAlertRequest_descriptor,
        new java.lang.String[] { "Actor", "FilterId", "TotalEvents", "DetectedAt", "SampleData", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
