// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/malicious_alert_service/v1/service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.malicious_alert_service.v1;

public interface RecordMaliciousEventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threat_protection.service.malicious_alert_service.v1.RecordMaliciousEventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.threat_protection.message.malicious_event.v1.MaliciousEventMessage malicious_event = 1 [json_name = "maliciousEvent"];</code>
   * @return Whether the maliciousEvent field is set.
   */
  boolean hasMaliciousEvent();
  /**
   * <code>.threat_protection.message.malicious_event.v1.MaliciousEventMessage malicious_event = 1 [json_name = "maliciousEvent"];</code>
   * @return The maliciousEvent.
   */
  com.akto.proto.threat_protection.message.malicious_event.v1.MaliciousEventMessage getMaliciousEvent();
  /**
   * <code>.threat_protection.message.malicious_event.v1.MaliciousEventMessage malicious_event = 1 [json_name = "maliciousEvent"];</code>
   */
  com.akto.proto.threat_protection.message.malicious_event.v1.MaliciousEventMessageOrBuilder getMaliciousEventOrBuilder();

  /**
   * <code>repeated .threat_protection.message.sample_request.v1.SampleMaliciousRequest sample_requests = 2 [json_name = "sampleRequests"];</code>
   */
  java.util.List<com.akto.proto.threat_protection.message.sample_request.v1.SampleMaliciousRequest> 
      getSampleRequestsList();
  /**
   * <code>repeated .threat_protection.message.sample_request.v1.SampleMaliciousRequest sample_requests = 2 [json_name = "sampleRequests"];</code>
   */
  com.akto.proto.threat_protection.message.sample_request.v1.SampleMaliciousRequest getSampleRequests(int index);
  /**
   * <code>repeated .threat_protection.message.sample_request.v1.SampleMaliciousRequest sample_requests = 2 [json_name = "sampleRequests"];</code>
   */
  int getSampleRequestsCount();
  /**
   * <code>repeated .threat_protection.message.sample_request.v1.SampleMaliciousRequest sample_requests = 2 [json_name = "sampleRequests"];</code>
   */
  java.util.List<? extends com.akto.proto.threat_protection.message.sample_request.v1.SampleMaliciousRequestOrBuilder> 
      getSampleRequestsOrBuilderList();
  /**
   * <code>repeated .threat_protection.message.sample_request.v1.SampleMaliciousRequest sample_requests = 2 [json_name = "sampleRequests"];</code>
   */
  com.akto.proto.threat_protection.message.sample_request.v1.SampleMaliciousRequestOrBuilder getSampleRequestsOrBuilder(
      int index);
}
