// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/malicious_alert_service/v1/service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.malicious_alert_service.v1;

public interface RecordMaliciousEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threat_protection.service.malicious_alert_service.v1.RecordMaliciousEventResponse)
    com.google.protobuf.MessageOrBuilder {
}
