// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/malicious_alert_service/v1/consumer_service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.malicious_alert_service.v1;

public interface RecordAlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threat_protection.service.malicious_alert_service.v1.RecordAlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string actor = 1 [json_name = "actor"];</code>
   * @return The actor.
   */
  java.lang.String getActor();
  /**
   * <code>string actor = 1 [json_name = "actor"];</code>
   * @return The bytes for actor.
   */
  com.google.protobuf.ByteString
      getActorBytes();

  /**
   * <code>string filter_id = 2 [json_name = "filterId"];</code>
   * @return The filterId.
   */
  java.lang.String getFilterId();
  /**
   * <code>string filter_id = 2 [json_name = "filterId"];</code>
   * @return The bytes for filterId.
   */
  com.google.protobuf.ByteString
      getFilterIdBytes();

  /**
   * <code>int32 total_events = 3 [json_name = "totalEvents"];</code>
   * @return The totalEvents.
   */
  int getTotalEvents();

  /**
   * <code>int64 detected_at = 4 [json_name = "detectedAt"];</code>
   * @return The detectedAt.
   */
  long getDetectedAt();

  /**
   * <code>repeated .threat_protection.service.malicious_alert_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  java.util.List<com.akto.proto.threat_protection.service.malicious_alert_service.v1.SampleMaliciousEvent> 
      getSampleDataList();
  /**
   * <code>repeated .threat_protection.service.malicious_alert_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  com.akto.proto.threat_protection.service.malicious_alert_service.v1.SampleMaliciousEvent getSampleData(int index);
  /**
   * <code>repeated .threat_protection.service.malicious_alert_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  int getSampleDataCount();
  /**
   * <code>repeated .threat_protection.service.malicious_alert_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  java.util.List<? extends com.akto.proto.threat_protection.service.malicious_alert_service.v1.SampleMaliciousEventOrBuilder> 
      getSampleDataOrBuilderList();
  /**
   * <code>repeated .threat_protection.service.malicious_alert_service.v1.SampleMaliciousEvent sample_data = 5 [json_name = "sampleData"];</code>
   */
  com.akto.proto.threat_protection.service.malicious_alert_service.v1.SampleMaliciousEventOrBuilder getSampleDataOrBuilder(
      int index);
}
