// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/service/malicious_alert_service/v1/service.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.service.malicious_alert_service.v1;

public final class ServiceProto {
  private ServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      ServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBthreat_protection/service/malicious_al" +
      "ert_service/v1/service.proto\0224threat_pro" +
      "tection.service.malicious_alert_service." +
      "v1\032:threat_protection/message/malicious_" +
      "event/v1/message.proto\0329threat_protectio" +
      "n/message/sample_request/v1/message.prot" +
      "o\"\036\n\034RecordMaliciousEventResponse\"\371\001\n\033Re" +
      "cordMaliciousEventRequest\022l\n\017malicious_e" +
      "vent\030\001 \001(\0132C.threat_protection.message.m" +
      "alicious_event.v1.MaliciousEventMessageR" +
      "\016maliciousEvent\022l\n\017sample_requests\030\002 \003(\013" +
      "2C.threat_protection.message.sample_requ" +
      "est.v1.SampleMaliciousRequestR\016sampleReq" +
      "uests2\331\001\n\025MaliciousEventService\022\277\001\n\024Reco" +
      "rdMaliciousEvent\022Q.threat_protection.ser" +
      "vice.malicious_alert_service.v1.RecordMa" +
      "liciousEventRequest\032R.threat_protection." +
      "service.malicious_alert_service.v1.Recor" +
      "dMaliciousEventResponse\"\000B\272\002\nCcom.akto.p" +
      "roto.threat_protection.service.malicious" +
      "_alert_service.v1B\014ServiceProtoP\001\242\002\003TSM\252" +
      "\0021ThreatProtection.Service.MaliciousAler" +
      "tService.V1\312\0021ThreatProtection\\Service\\M" +
      "aliciousAlertService\\V1\342\002=ThreatProtecti" +
      "on\\Service\\MaliciousAlertService\\V1\\GPBM" +
      "etadata\352\0024ThreatProtection::Service::Mal" +
      "iciousAlertService::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akto.proto.threat_protection.message.malicious_event.v1.MessageProto.getDescriptor(),
          com.akto.proto.threat_protection.message.sample_request.v1.MessageProto.getDescriptor(),
        });
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventResponse_descriptor,
        new java.lang.String[] { });
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_threat_protection_service_malicious_alert_service_v1_RecordMaliciousEventRequest_descriptor,
        new java.lang.String[] { "MaliciousEvent", "SampleRequests", });
    descriptor.resolveAllFeaturesImmutable();
    com.akto.proto.threat_protection.message.malicious_event.v1.MessageProto.getDescriptor();
    com.akto.proto.threat_protection.message.sample_request.v1.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
