#!/usr/bin/env bash
# install-shell-hooks.sh - install Akto claude-cli-ARGUS shell hooks (no python/jq).
# Argus mode: uses AKTO_HOST (default api.anthropic.com), device IP, no atlas device URL.
set -eu
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INGESTION_URL="${AKTO_DATA_INGESTION_URL:-}"
AKTO_HOST_VAL="${AKTO_HOST:-https://api.anthropic.com}"
TARGET_HOME="$HOME"; SRC_BASH="$SRC_DIR/bash"
while [ $# -gt 0 ]; do case "$1" in
  --ingestion-url) INGESTION_URL="$2"; shift 2;;
  --akto-host) AKTO_HOST_VAL="$2"; shift 2;;
  --home) TARGET_HOME="$2"; shift 2;;
  --src) SRC_BASH="$2"; shift 2;;
  *) echo "unknown arg: $1" >&2; exit 2;; esac; done

HOOKS_DIR="$TARGET_HOME/.claude/hooks"; SETTINGS="$TARGET_HOME/.claude/settings.json"
log() { echo "[Akto argus shell-hooks] $1"; }
mkdir -p "$HOOKS_DIR"
for f in akto_common.sh akto-validate-prompt.sh akto-validate-response.sh akto-validate-mcp-request.sh akto-validate-mcp-response.sh; do
  cp "$SRC_BASH/$f" "$HOOKS_DIR/$f"; chmod +x "$HOOKS_DIR/$f"
done
log "Installed argus bash hooks + akto_common.sh"

make_wrapper() {
  local name="$1"
  local wf="$HOOKS_DIR/akto-validate-${name}-wrapper.sh"
  cat > "$wf" <<EOF
#!/bin/bash
# Auto-generated by Akto argus shell-hooks installer (runtime-detecting)
export AKTO_DATA_INGESTION_URL="$INGESTION_URL"
export AKTO_HOST="$AKTO_HOST_VAL"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="claude_code_cli"
export AKTO_CONNECTOR_VALUE="claudecli"
export CONTEXT_SOURCE="AGENTIC"
export LOG_LEVEL="INFO"
HOOKS_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
if command -v python3 >/dev/null 2>&1 && [ "\${AKTO_HOOK_RUNTIME:-}" != "shell" ] && [ -f "\$HOOKS_DIR/akto-validate-${name}.py" ]; then
  exec python3 "\$HOOKS_DIR/akto-validate-${name}.py" "\$@"
else
  exec bash "\$HOOKS_DIR/akto-validate-${name}.sh" "\$@"
fi
EOF
  chmod +x "$wf"
}
for n in prompt response mcp-request mcp-response; do make_wrapper "$n"; done
log "Generated runtime-detecting wrappers"

P="$HOOKS_DIR/akto-validate-prompt-wrapper.sh"; R="$HOOKS_DIR/akto-validate-response-wrapper.sh"
PRE="$HOOKS_DIR/akto-validate-mcp-request-wrapper.sh"; POST="$HOOKS_DIR/akto-validate-mcp-response-wrapper.sh"
[ -f "$SETTINGS" ] && cp "$SETTINGS" "$SETTINGS.backup.$(date +%s)"
mkdir -p "$(dirname "$SETTINGS")"
cat > "$SETTINGS" <<EOF
{
  "hooks": {
    "UserPromptSubmit": [ { "hooks": [ { "type": "command", "command": "$P", "timeout": 10 } ] } ],
    "Stop":             [ { "hooks": [ { "type": "command", "command": "$R", "timeout": 10 } ] } ],
    "PreToolUse":       [ { "hooks": [ { "type": "command", "command": "$PRE", "timeout": 10 } ] } ],
    "PostToolUse":      [ { "hooks": [ { "type": "command", "command": "$POST", "timeout": 10 } ] } ]
  }
}
EOF
log "Wrote settings.json. Done."
