// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/message/sample_request/v1/message.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.message.sample_request.v1;

public final class MessageProto {
  private MessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      MessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_threat_protection_message_sample_request_v1_SampleMaliciousRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_threat_protection_message_sample_request_v1_SampleMaliciousRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9threat_protection/message/sample_reque" +
      "st/v1/message.proto\022+threat_protection.m" +
      "essage.sample_request.v1\"\323\001\n\026SampleMalic" +
      "iousRequest\022\016\n\002ip\030\001 \001(\tR\002ip\022\034\n\ttimestamp" +
      "\030\002 \001(\003R\ttimestamp\022\020\n\003url\030\003 \001(\tR\003url\022\026\n\006m" +
      "ethod\030\004 \001(\tR\006method\022*\n\021api_collection_id" +
      "\030\005 \001(\005R\017apiCollectionId\022\030\n\007payload\030\006 \001(\t" +
      "R\007payload\022\033\n\tfilter_id\030\007 \001(\tR\010filterIdB\221" +
      "\002\n:com.akto.proto.threat_protection.mess" +
      "age.sample_request.v1B\014MessageProtoP\001\242\002\003" +
      "TMS\252\002)ThreatProtection.Message.SampleReq" +
      "uest.V1\312\002)ThreatProtection\\Message\\Sampl" +
      "eRequest\\V1\342\0025ThreatProtection\\Message\\S" +
      "ampleRequest\\V1\\GPBMetadata\352\002,ThreatProt" +
      "ection::Message::SampleRequest::V1b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_threat_protection_message_sample_request_v1_SampleMaliciousRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_threat_protection_message_sample_request_v1_SampleMaliciousRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_threat_protection_message_sample_request_v1_SampleMaliciousRequest_descriptor,
        new java.lang.String[] { "Ip", "Timestamp", "Url", "Method", "ApiCollectionId", "Payload", "FilterId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
