// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threat_protection/message/sample_request/v1/message.proto
// Protobuf Java Version: 4.28.3

package com.akto.proto.threat_protection.message.sample_request.v1;

public interface SampleMaliciousRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:threat_protection.message.sample_request.v1.SampleMaliciousRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1 [json_name = "ip"];</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1 [json_name = "ip"];</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int64 timestamp = 2 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string url = 3 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string method = 4 [json_name = "method"];</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 4 [json_name = "method"];</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>int32 api_collection_id = 5 [json_name = "apiCollectionId"];</code>
   * @return The apiCollectionId.
   */
  int getApiCollectionId();

  /**
   * <code>string payload = 6 [json_name = "payload"];</code>
   * @return The payload.
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 6 [json_name = "payload"];</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();

  /**
   * <code>string filter_id = 7 [json_name = "filterId"];</code>
   * @return The filterId.
   */
  java.lang.String getFilterId();
  /**
   * <code>string filter_id = 7 [json_name = "filterId"];</code>
   * @return The bytes for filterId.
   */
  com.google.protobuf.ByteString
      getFilterIdBytes();
}
