#!/bin/bash
# Auto-generated wrapper for Akto guardrails hook
# Generated by MCP Endpoint Shield installer

export MODE="atlas"
export AKTO_DATA_INGESTION_URL="{{AKTO_DATA_INGESTION_URL}}"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
# TODO: Change to "cursor" connector once backend support is added
export AKTO_CONNECTOR="claude_code_cli"

# Execute Python hook script
exec python3 "$HOME/.cursor/hooks/akto/akto-validate-chat-prompt.py" "$@"
