#!/bin/bash
# Auto-generated wrapper for Akto guardrails hook
# Generated by MCP Endpoint Shield installer

export MODE="atlas"
export AKTO_DATA_INGESTION_URL="{{AKTO_DATA_INGESTION_URL}}"
export AKTO_SYNC_MODE="true"
export AKTO_TIMEOUT="5"
export AKTO_CONNECTOR="cursor"
export CONTEXT_SOURCE="ENDPOINT"
export DEVICE_ID="{{DEVICE_ID (optional)}}"
export VALIDATE_FILES="true"
export FILE_MAX_BYTES="5242880"

export LOG_LEVEL="INFO"
export LOG_PAYLOADS="false"

exec python3 "$HOME/.cursor/hooks/akto/akto-validate-before-read-file.py" "$@"
